### ISSUE TITLE
Unhandled errors present while scrolling feed

### ISSUE THREAD

**Issue by mormaer** [mlemgroup/mlem#100]
During internal testing of the `0.0.7 (23)` build there have been reports of the following error message appearing repeatedly as the user scrolls their feed:

> "Sorry, something unexpected happened. Please try again"

This is the default messaging in place when catching the `.unexpected` case from this request.

This suggests that the failure is occurring when we try to encode our request body (however loading posts is a `GET` with queries so unlikely!) or that we are failing to decode our response. This may point to differences between instances.

We need to find a way to easily reproduce this error so that we can locate the cause and fix.

**Comment by EricBAndrews** [comment]
Still present?

**Comment by EricBAndrews** [comment]
Closing as stale and also too vague
