### ISSUE TITLE
App Review Compliance

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#1011]
Per App Store email:

> Hello,
> 
> We noticed one or more issues with a recent submission for TestFlight review for the following app:
> 
>     Mlem for Lemmy
>     Version 1.3
>     Build 913
> 
> Although submission for TestFlight review was successful, you may want to correct the following issues in your next submission for TestFlight review. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Mlem” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> Apple Developer Relations

Suggested fix is to remove use of `UserDefaults` in favor of `@AppStorage`; if that is not possible, we can cite reason `CA92.1`.

**Comment by Sjmarf** [comment]
Hmm, that's interesting. 

I don't think removing `UserDefaults` usages would make us compliant, though? `@AppStorage` uses `UserDefaults` under the hood, so I imagine it would also count. That is, unless accessing the `UserDefaults` API directly instead of via `AppStorage` allows for a wider range of access that isn't possible with `AppStorage`, or something.

**Comment by Sjmarf** [comment]
I found this, could be useful

https://github.com/Wooder/ios_17_required_reason_api_scanner

**Comment by EricBAndrews** [comment]
Interesting! The [App Store guidelines](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) mention `UserDefaults` but do not include `@AppStorage`. It would be a little weird for Apple to require a privacy declaration for such a standard feature of SwiftUI--let's try just explicit `UserDefaults` calls, and if Apple still complains, we can provide a reason declaration.

**Comment by Sjmarf** [comment]
Closed in #1043
