### ISSUE TITLE
* Mark read on scroll marks it too early

### ISSUE THREAD

**Issue by slrgt** [mlemgroup/mlem#1018]
**Describe the bug**
When scrolling down the feed posts are marked as read when they're barely halfway through the screen.

**Expected Behavior**
Is they were marked after they left the screen it would make it easier to read before it turning a darker color

**To Reproduce**
Scroll with Mark read on scroll turned on

**Mlem Information:**
1.3 (913)

**Comment by d42ohpaz** [comment]
I agree with poster. I wanted to add that from a UX perspective, it's a little jarring to have the post be marked read almost immediately. Delaying the marked read until after it moves off screen would feel more natural.
