### ISSUE TITLE
UI bug clipping one post into another

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#103]
![image](https://github.com/mormaer/Mlem/assets/22740616/9ff14d52-b02b-4fdd-957a-003d6185debc)

0.0.7 (5)

**Comment by EricBAndrews** [comment]
Is this bug still present?

**Comment by ShadowJonathan** [comment]
I haven't observed it, I'll re-open if I see it again, or in TFF

**Comment by ShadowJonathan** [comment]
I observed it again, build 39

![image](https://github.com/mlemgroup/mlem/assets/22740616/9d4fa6c9-aa57-4ee6-bbd6-820c35f40283)

**Comment by JiimBob** [comment]
Looks like this may have been fixed in #225 

Tried a few tall text and image posts but couldn't get anything to clip.

**Comment by EricBAndrews** [comment]
Issue seems long gone, closing as completed.
