### ISSUE TITLE
New post panel gets stuck mid page * 

### ISSUE THREAD

**Issue by capybeby** [mlemgroup/mlem#104]
**Describe the bug**
What did you do to trigger the bug?
If the new post panel is open and a post is clicked on, when one returns to the community page, the new post panel is floating in the middle of the page.

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug
0.1.0

**Additional Context**
Any other relevant information

screen recording of bug:
https://github.com/mormaer/Mlem/assets/137654063/0415fcaa-d2bb-498f-8b0f-b88359b92502

**Comment by EricBAndrews** [comment]
Stale, that post panel has been yote altogether

Thanks for the bug report ❤️
