### ISSUE TITLE
Collapsing comments can overlap with post

### ISSUE THREAD

**Issue by made2k** [mlemgroup/mlem#1041]
**Describe the bug**
When collapsing comments, especially towards the top of the comment chain, large comments and especially those with embedded images can overlay the post. This is a very minor visual only glitch.

**Expected Behavior**
When comments collapse, they should not overlap with the post content.

**Actual Behavior**
Comments can overlap with the post. I took a video and the results can be seen in the post. It can be reproduced well on the post located at: https://lemmy.world/post/14696898.

https://github.com/mlemgroup/mlem/assets/1799888/7e74cd88-a016-4cc7-b39b-871697304eda

**To Reproduce**
Visit the lemmy post [here](https://lemmy.world/post/14696898) inside the mlem app and collapse the comments to have the image embedded in a comment overlap the post content when it is collapsed.

**Mlem Information:**
v1.2 (847)

**Comment by made2k** [comment]
There seems to be a relatively simple fix for this that can be seen [here](https://github.com/mlemgroup/mlem/compare/dev...made2k:mlem:clip-comment-collapse?expand=1). I'd be happy to open a PR to get this resolved especially if clipping the comments seem like a reasonable approach.

I've only started looking into the repo though so if you believe there's a better approach to fixing this let me know and I could work elsewhere before opening a PR. Thanks!

**Comment by Sjmarf** [comment]
Nice, feel free to open a PR 👍
