### ISSUE TITLE
Set a max height for images

### ISSUE THREAD

**Issue by wi-ry** [mlemgroup/mlem#109]
## Introduction
Someone posted a long image in lemmy.ca/c/main and it covered like four pages of scrolling

## Requirements
Set a max height (and width?) for images and shrink them to fit that area. When pressed the full image could be shown. 

## Discussion
I think I covered that above

## What I Need
I think I covered that too

![image](https://github.com/buresdv/Mlem/assets/9650258/f3ba3420-512e-4cdd-aee6-4ede132b811f)

**Comment by fer0n** [comment]
@EricBAndrews I think this one can be closed, right?

**Comment by wi-ry** [comment]
Yeah, I haven't had this issue recently
