### ISSUE TITLE
Reply function occasionally stops working

### ISSUE THREAD

**Issue by 0xCmdrKeen** [mlemgroup/mlem#1102]
**Describe the bug**
I'm not sure exactly what causes this to happen, but occasionally, the reply function simply stops working. Neither tapping the button nor using the swipe gesture will bring up the required dialog. This seems to happen more often when the app is put into the background.

This also affects the "new post" function.

**Expected Behavior**
The reply dialog should come up consistently every time the button is pressed or the corresponding swipe gesture is used.

**Actual Behavior**
The reply dialog sometimes does not show up.

**To Reproduce**
As mentioned before, I do not know what causes this, but it seems to happen more often when the app is frequently put in the background.

**Mlem Information:**
Mlem 1.3.1 (996)

**Comment by 0xCmdrKeen** [comment]
Just tested the new release from the App Store (1.3.2 Build 982) and it is also affected.

**Comment by Sjmarf** [comment]
I don't think this happens anymore in v2
