### ISSUE TITLE
Popup a dismissible alert if a user is trying to interact with an instance that is blocked with the current one.

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#112]
Currently I see that beehaw.org is defederating with a lot of instances.

That's understandable, but when I tried searching for communities on instances my current server had blocked, I didn't get any feedback, so we should notify the user about that.

In this instance, the community was on lemmy.world, while beehaw.org had blocked that.

**Comment by EricBAndrews** [comment]
This feels pretty easy from the frontend as long as we have good backend. Slating for 1.2.

**Comment by EricBAndrews** [comment]
Should be fixed with 2.0 middleware--non-interactable content is opened in guest mode with notice
