### ISSUE TITLE
The '…' Button Not Working When Replying to a Comment

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1122]
**Describe the bug**
When I tap the '…' button in a comment reply, nothing happens. 

**Expected Behavior**
A submenu with options. 

**Actual Behavior**
Nothing. 

**Mlem Information:**
v1.3.3 (994)
iOS 17.5.2
iPhone 12 Pro Max

**Comment by Sjmarf** [comment]
Fixed in 2.0
