### ISSUE TITLE
Provide a screen with instance details

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#115]
Instances (under GetSite) provide a lot of details about the current instance, such as discussion languages, description, moderators, and other things. We should expose this in the app, and provide a way for a user to look up this information in-app.

**Comment by EricBAndrews** [comment]
Putting as 1.1. Related to #206

**Comment by Sjmarf** [comment]
I'd like to work on this one after I finish working on Settings, if no-one else is already.
