### ISSUE TITLE
Better visual separation between post and comments

### ISSUE THREAD

**Issue by Emiliaaah** [mlemgroup/mlem#117]
## Introduction
Currently I find that the separation between a post and it's comments is very much lacking. There's a few ways to tell, but i think there should be a clear distinction.

It currently looks like this:
![image](https://github.com/mormaer/Mlem/assets/55017867/2ea348fe-32ac-4c49-9fe1-6a3ef59f20d6)

Here's how Apollo does it, to give you an example:
![image](https://github.com/mormaer/Mlem/assets/55017867/2acfb7cd-ca6f-4f95-b22e-52d89f511bcc)

## Requirements
The UI for the post view should be changed to make a clearer distinction between the post and the comments for that post.

**Comment by EricBAndrews** [comment]
Putting down for 1.1, tweaks to the expanded post are coming then

**Comment by EricBAndrews** [comment]
Fixed in 2.0 design updates
