### ISSUE TITLE
Keyword filtering

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#1175]
> [!important]
> Post from communities you moderate should never be hidden.

**Comment by d42ohpaz** [comment]
Given recent events in America, I feel that keyword filtering might be a good idea to help with people's mental health. 😕

**Comment by Sjmarf** [comment]
Yeah. We've done half of the work to get this working again already; it's just the UI stuff left essentially. It'll be back in before 2.0 release.
