### ISSUE TITLE
Setup TestFlight nightlies

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#119]
We want github to deploy nightly builds for us to testflight, so we could continually improve and test the latest builds, until we're satisfied, and then deploy the build to a wider audience.

We can do this in GHA CI via Fastlane (one blogpost ive come across is [this](https://litoarias.medium.com/continuous-delivery-for-ios-using-fastlane-and-github-actions-edf62ee68ecc) one), and we can separate the public testing with internal test groups.

For inviting people to the internal test groups, and getting the appropriate credentials, certificates, and more for the fastlane/testflight management, we'd need some of @buresdv's involvement.

One concern would be that since this is running every night, and we may not have movement on master for a full 24h, we may be making duplicate builds for nothing, ~~I would see if its possible to not run GHA in this case, though if not, it wouldn't be a huge deal.~~ It is possible: https://stackoverflow.com/a/67527144/8700553

**Comment by EricBAndrews** [comment]
Closed because done, don't think there's a PR because it's all Xcode
