### ISSUE TITLE
Publish to AltStore with each release

### ISSUE THREAD

**Issue by silentsilas** [mlemgroup/mlem#123]
## Introduction
Currently, the TestFlight beta is full. Technically-inclined users would be able to work around this by side-loading the IPA via AltStore. 

## Requirements
* Create an IPA via Xcode
* Host it somewhere, lots of projects automate it with Github Releases
* Follow this [guide](https://faq.altstore.io/sources/make-a-source) to create a "source" that users can paste into AltStore to install the app

## Discussion
Users with a paid Apple developer account can install it by adding the bundle identifier to their account and exporting an archive. This requires a Mac, $99 for the developer account, and the technical know-how to use Xcode to build an IPA under their Apple team. A publicly-available IPA and/or publishing to AltStore would let users without a Mac or paid developer account sideload the app.

## What I Need
Essentially, the X Y problem is the need for an alternative method to install the app while the Testflight beta is full.

**Comment by EricBAndrews** [comment]
Tentatily closing as not planned, as we haven't heard a lot of enthusiasm for this--if highly requested we may revisit.
