### ISSUE TITLE
Change "New" post sorting option icon

### ISSUE THREAD

**Issue by Emiliaaah** [mlemgroup/mlem#126]
## Introduction
I'm personally not a big fan of the sun icon for "New" sorting option for posts and comments. So I'd like to propose that we change this.

Preview of what it looks like currently:
![image](https://github.com/mormaer/Mlem/assets/55017867/fad74d28-71f3-4218-babb-ac32321d69ca)

I think it's a bit confusing when it looks like this:
![image](https://github.com/mormaer/Mlem/assets/55017867/c6522de0-716a-488d-ad1a-84fafe902fba)

## Requirements
What needs to be done?

## Discussion
Since this is highly personal I'd like to hear other people's opinion on changing this, since this could just be a me thing. So feel free to let me know if you feel the same way and if you do what icon you'd like for it to be instead.

## What I Need
That the icon for the "New" post and comment sorting option is changed to whatever is decided by the discussions here.

**Comment by Sjmarf** [comment]
I'm undecided on this one. Here are two clock icons that could work well. Reddit uses a 'seal' symbol (bottom), which could be a good fit too. 

<img width="430" alt="Screenshot 2023-07-13 at 20 32 27" src="https://github.com/mlemgroup/mlem/assets/78750526/3398a2f9-78af-4e6b-8660-2d6761b60d31">

(All 4 of these are from SF Symbols)
