### ISSUE TITLE
Import/Export Settings

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#1268]
Add a feature to save settings to a JSON file. This can also support migrating settings from v1 to v2.

**Comment by Sjmarf** [comment]
AppStorage values are still present from v1, right? Couldnt we do this automatically without JSON?

**Comment by EricBAndrews** [comment]
We could, but this approach also lets us create a manual import/export function that users can use to move settings across devices or backup or whatever else they want--it's also IMO cleaner to have our 2.0 codebase be entirely ignorant of the v1 `AppStorage` and have an encoded file serve as a middle ground.
