### ISSUE TITLE
Show Account Age next to post creator

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#1270]
![image](https://github.com/user-attachments/assets/6bebb685-66a0-4696-ad1f-580a7c2b8683)

Requested here: https://lemmy.ml/post/19667288/13318847

**Comment by norahqueen** [comment]
Hey! I'm Norah, I requested this feature. I just wanted to check on the implementation. When an account is less than 24hrs old, Voyager/Apollo display <1d. I think this is specifically the one I look out for the most, especially when a comment is already questionable. 

Also thanks for implementing it so quickly! Can't wait to see it in the weekly.

**Comment by Sjmarf** [comment]
Hey @norahqueen, it'll show a number of hours if the account is less than a day old. We'll have another weekly out today or tomorrow :)
