### ISSUE TITLE
Clicking on a reply in your inbox takes you to the top of the thread, not the reply as it has previously.

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#1281]
Maybe has to do with lazy loading?

**Comment by Sjmarf** [comment]
Yeah, I noticed this. It seems to work sometimes but not other times.

**Comment by d42ohpaz** [comment]
So far, this seems to be fixed in 2.0 (57). I've clicked on many replies in my inbox and they all load at the appropriate comment.

**Comment by Sjmarf** [comment]
We also did some additional work towards fixing this [here](https://github.com/mlemgroup/mlem/pull/1297), which isn't live yet. It's still not quite perfect though - posts with massive body text seem to trip it up. Leaving open for now

**Comment by EricBAndrews** [comment]
Fixed with comment page
