### ISSUE TITLE
[2.0] Bring Back Old Comment/Reply Sheet

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1288]
## Introduction
In 1.x, the comment/reply sheet had a couple of vital features that are now missing from 2.0:

- Showing the original poster@community
- The ability to collapse the comment/reply and interact with the post or other comments as a reference
- Albeit, it never worked (for me), but what appeared to be controls to allow copying text from the post/comment

## Discussion
The old comment/reply sheet was unique in that it allowed me to go back and refresh my (adhd-riddled) memory about the post or other comments made by other people. It really allowed a more complete picture than what I was commenting/replying on, as I could also browse back in my feed if I needed to look something up. 

It wasn't without its own issues, but the new comment/reply sheet feels like throwing the baby out with the bath water. 

## What I Need
[I'll buy you all coffees](https://blog.warengonzaga.com/how-to-enable-buy-me-a-coffee-to-your-open-source-project-on-github)

**Comment by Sjmarf** [comment]
> Showing the original poster@community

Sure, we can add this back in.

> The ability to collapse the comment/reply and interact with the post or other comments as a reference

You can still do this in v2, but you need to type something in the comment sheet first. If you haven't typed anything yet, it closes the sheet. We made the collapsed sheet go down further on the screen in v2 for easier viewing of the content behind it. If this definitely isn't working lmk

> Albeit, it never worked (for me), but what appeared to be controls to allow copying text from the post/comment

I'm not sure what you're referring to. The "Paste" button in the post creator was for pasting an image from the clipboard and uploading it. We'll be keeping that when we redo the post creator for v2. We never had a dedicated button for copying text I don't think.

**Comment by d42ohpaz** [comment]
> > The ability to collapse the comment/reply and interact with the post or other comments as a reference
> 
> 
> 
> You can still do this in v2, but you need to type something in the comment sheet first. If you haven't typed anything yet, it closes the sheet. We made the collapsed sheet go down further on the screen in v2 for easier viewing of the content behind it. If this definitely isn't working lmk

Got it! I tested it and yes it is working. And the going down further is perfect. 

> > Albeit, it never worked (for me), but what appeared to be controls to allow copying text from the post/comment
> 
> 
> 
> I'm not sure what you're referring to. The "Paste" button in the post creator was for pasting an image from the clipboard and uploading it. We'll be keeping that when we redo the post creator for v2. We never had a dedicated button for copying text I don't think.

In v1 there was a "..." icon in the top-right of the comment sheet. I never could get it to work, but I always assumed that like the "..." on posts and comments (before replying -- see screenshot below) it would allow selecting text for quoting a post or comment (#1122). 

![image](https://github.com/user-attachments/assets/ecbe6dd6-5e99-4389-bcde-7815dd5d8fa2)

**Comment by Sjmarf** [comment]
> In v1 there was a "..." icon in the top-right of the comment sheet. I never could get it to work, but I always assumed that like the "..." on posts and comments (before replying -- see screenshot below) it would allow selecting text for quoting a post or comment (https://github.com/mlemgroup/mlem/issues/1122).

Ah, I see what you mean. Showing the `...` was an unintentional consequence of reusing the UI logic we use to render the actual posts/comments - it wasn't functional. It being there was confusing, which is why we removed it in 2.0. We can definitely add a "select text" button there 👍
