### ISSUE TITLE
crash on latest iOS 18 public beta

### ISSUE THREAD

**Issue by umrath** [mlemgroup/mlem#1295]
mlem crashes when opening the app on the latest iOS 18 public beta.
The behaviour is consistantly reproducible.

It crashes right on startup without any further messages, activities or the like.

**Comment by Sjmarf** [comment]
Are you on the TestFlight or the App Store build?

**Comment by umrath** [comment]
AppStore

**Comment by Sjmarf** [comment]
I'm unable to reproduce this at the moment using my iOS 18 device. When did this start happening - when you updated to iOS 18, or at a different time? If you delete the app and reinstall it, does the issue persist?

**Comment by umrath** [comment]
Damn, forgot the most obvious thing!
Yes, it works again when reinstalling.

Started with the latest (6th?) beta.

**Comment by umrath** [comment]
Problem was not the app but the user.
