### ISSUE TITLE
User Labels

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#1299]
Needs a more robust persistence system. We'll need such a system to handle a bunch of multi-account complexities anyway, so we can bolt this feature on once we have it in place.

**Comment by Sjmarf** [comment]
Possible clone of #1085?

Requires #1133

**Comment by ghost** [comment]
Also it would be nice for the app to show a list of users with their tags beside them so that anyone could export for desktop use too.

**Comment by Sjmarf** [comment]
Yeah, that's a good idea.

Closing as duplicate of #1085
