### ISSUE TITLE
Add more granular controls to User and Community tags settings to address user requests for a more Apollo-like Compact View

### ISSUE THREAD

**Issue by BrooklynMan** [mlemgroup/mlem#13]
some users want a more Apollo-like Compact view. This can be achieved easily by creating more granular settings for information display in the User and Community tags, especially in the main feed.

By providing individual toggles for the users to enable/disable Avatars and/or instance addresses for users, communities, or both in every context in which they may appear (posts, comments, etc.), the users will be able to create an experience as much or as little like the Compact view in Apollo as they like with minimal changes to our current code base.

**Comment by WestonHanners** [comment]
I want this after I finish comments.

**Comment by jiannazzone** [comment]
Another thought: move the poster username and icon to the top right of the row in compact view.

![image](https://github.com/mlemgroup/mlem/assets/46025473/f17fcf72-d4c6-4e0f-8a69-cafcba1126f0)

**Comment by EricBAndrews** [comment]
Closed in #196
