### ISSUE TITLE
* Gifs in comments don't play

### ISSUE THREAD

**Issue by turnipjs** [mlemgroup/mlem#1306]
**Describe the bug**
Gifs that are embedded in comments (markdown(?)) do not play in normal view or after tapping on the image to enlarge it.

**Expected Behavior**
A way to view the gif animation.

I would personally like for gifs to not autoplay and: only play after tapping on them, or, only play in the full screen preview window In both of these cases there should be an icon with a drop shadow or background (for visibility) indicating that the still image preview is for a gif.

**Actual Behavior**
No way to see gif animation in app. One must copy link and view in browser. Additionally there is no indication that an image is a gif.

**To Reproduce**
[As seen in this comment.](https://lemmy.autism.place/comment/905002)
App version 1.3.3 (994) downloaded from Apple App Store.

**Mlem Information:**
App version 1.3.3 (994) downloaded from Apple App Store.

I believe it has always been this way for me (gifs don't play). I just today realized that people are posting gifs in comments when that still image preview didn't make any sense in context.

**Additional Context**
Any other relevant information
App was updated to current version from 1.0.3(?) obtained via TestFlight.

**Comment by EricBAndrews** [comment]
This is planned for 2.0--it's in development, should be in the 2.0 beta soon(ish)

**Comment by EricBAndrews** [comment]
Closed in #1365
