### ISSUE TITLE
[2.0] Unable to inline/upload images in comments/replies

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1324]
**Describe the bug**
In 1.x I used to be able to copy an image from any source (e.g., web browser, Photos.app, etc) and use the iOS Paste function to upload and inline the \!\[]\(...\) uploaded image -- just like when using the lemmy-ui in the browser. 

Also, the image icon in the editor toolbar does not appear to do anything. 

**Expected Behavior**
Double-tapping the screen should show the Paste option when I've copied an image.

I imagine that tapping the image icon in the editor icon should also provide a way to upload an image. 

**Actual Behavior**
Tapping the screen only shows the select/select all options; no paste. 

Tapping the image icon in the toolbar does not appear to do anything that I can see. 

**To Reproduce**
Make a comment and attempt to paste or upload an image. 

**Mlem Information:**
2.0 (57)

**Comment by Sjmarf** [comment]
> In 1.x I used to be able to copy an image from any source (e.g., web browser, Photos.app, etc) and use the iOS Paste function to upload and inline the ![](...) uploaded image -- just like when using the lemmy-ui in the browser.

I don't think this existed in v1? You used to be able to paste images from the image upload menu in the toolbar at the top of the screen in v1, but it wasn't the iOS "paste" button.

> Also, the image icon in the editor toolbar does not appear to do anything.

[I implemented this](https://github.com/mlemgroup/mlem/pull/1310) half an hour ago :) It'll be out in a TF release in the next day or two.
