### ISSUE TITLE
app crashes on iOS 18 when tapping the button to change the app icon.

### ISSUE THREAD

**Issue by nalabrie** [mlemgroup/mlem#1344]
**Describe the bug**
What did you do to trigger the bug?

Attempted to change the app icon

**Expected Behavior**
What did you expect to happen?

Not to crash

**Actual Behavior**
What actually happened?

Crashed :(

**To Reproduce**
What steps do I need to take to trigger the bug?

Press settings > appearance > app icon

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug

1.3.5 (59)

**Additional Context**
Any other relevant information

**Comment by glamoroussky** [comment]
For me, the latest version, iOS 18, iPhone 15 Pro, when taping "Appearance" in the setting, it immediately kill the whole app, and back to the Home Screen.

**Comment by nalabrie** [comment]
If it matters, I'm using an iPhone 14 Pro and the current app icon in use is the default one. I never changed the icon before, but on iOS 17 I remember looking through the icons in the settings at least once so I know the crash didn't happen then. My crash is also instantly to the Home Screen and is consistent.

**Comment by QuarterSwede** [comment]
> For me, the latest version, iOS 18, iPhone 15 Pro, when taping "Appearance" in the setting, it immediately kill the whole app, and back to the Home Screen.

Same problem on a 12 Pro Max.
