### ISSUE TITLE
The app logged me out unexpectedly (probably after an update)

### ISSUE THREAD

**Issue by hades** [mlemgroup/mlem#1345]
**Describe the bug**
What did you do to trigger the bug

Nothing (I suspect a new version was installed)

**Expected Behavior**
What did you expect to happen?

The app keeps my data and login information.

**Actual Behavior**
What actually happened?

I opened the app yesterday, and it presented me with a welcome screen ("I'm new here"/"I have a Lemmy account")

**To Reproduce**
What steps do I need to take to trigger the bug?

n/a

**Mlem Information:**
1.3.5

**Additional Context**
Any other relevant information

**Comment by wkeifenheim** [comment]
Same thing happened to me, I believe when 1.3.5 was released. In my case I can no longer log in using Mlem.
![IMG_1395](https://github.com/user-attachments/assets/8851a10c-a260-4fc5-a298-7e6cd0b014da)

**Comment by EricBAndrews** [comment]
The reauthentication behavior is due to the app moving from Lionel Hanners' account to mine--we use Keychain to store authentication information, which for security reasons is tied to the app owner's account. 

I'm not sure why reauthentication is failing--have you tried uninstalling the app and reinstalling?

**Comment by wkeifenheim** [comment]
> The reauthentication behavior is due to the app moving from Lionel Hanners' account to mine--we use Keychain to store authentication information, which for security reasons is tied to the app owner's account.
> 
> I'm not sure why reauthentication is failing--have you tried uninstalling the app and reinstalling?

Gave that another try just now. I get a green check mark for half a second then the same error message as before.

edit: Figured it out. My password manager was using my email for login, which works on the browser but not Mlem. Switched it to username and Mlem is working again. Unless someone else has more issues logging in, this GitHub issue seems like a _no action needed_ one.

**Comment by hades** [comment]
thanks for the explanation, and thanks for your work on mlem, I've only been using it for a couple of weeks, and so far it worked flawlessly!

maybe consider adding a message when the credentials are deleted due to key store change? otherwise the impression is that the app has lost all the data.

thanks again!
