### ISSUE TITLE
Images in Some Posts Not Loading

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1353]
**Describe the bug**
Some image posts do not load and show the question mark with a dashed box border icon. Long-pressing and choosing Quick Look provides and Error toast. 

**Expected Behavior**
The image to load and be disable via Quick Look. 

**Actual Behavior**
![image](https://github.com/user-attachments/assets/13f0bbff-0e12-455b-bbd6-a3138d374d7b)

**To Reproduce**
https://sh.itjust.works/post/25527697

**Mlem Information:**
2.0 (68)

**Additional Context**
iOS 18

**Comment by Sjmarf** [comment]
This looks like an issue with the `lemmy.world` image proxy, as the image also fails to load there. https://lemmy.world/post/20025488
![Screenshot 2024-09-21 at 21 34 33](https://github.com/user-attachments/assets/4458297f-c1f9-4a49-928d-99082b9ccdc9)
