### ISSUE TITLE
* Cannot login to lemmy.world

### ISSUE THREAD

**Issue by rustingrooster** [mlemgroup/mlem#1359]
**Describe the bug**
What did you do to trigger the bug?
Logging into mlem with a lemmy.world user result in a gremen checkmark and a return to the login screen. 

**Expected Behavior**
What did you expect to happen?
Successful login

**Actual Behavior**
What actually happened?
Green checkmark then reprompted for login. “Mlem couldnt fetch your accounts information. File a bug report”

**To Reproduce**
What steps do I need to take to trigger the bug?
Login with a lemmy.world userid. I have verified that the username and password are correct on lemmy.world. 

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug
Ios 1.3.6. Started happening several days ago. 

**Additional Context**
Any other relevant information
Thank you.

**Comment by EricBAndrews** [comment]
Unable to reproduce--is this issue still present on 1.3.7?

**Comment by abbec** [comment]
I have the exact same issue for lemmy.zip on 1.3.7.

**Comment by abbec** [comment]
It does work fine with username instead of email though. Maybe that is the issue for OP as well?

**Comment by rustingrooster** [comment]
Yes thats what it turned out to be. I was using email address and got the
failure. Once i switched to username login was successful.

**Comment by Rexios80** [comment]
I couldn't log in to lemmy.zip with my username but email worked
