### ISSUE TITLE
When sharing to Mlem, test if its an open-able URL first

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#137]
This could be done through the resolve-object endpoint, where we first look if the URL given is a resolvable one, and if it is, show that community/post/comment/user, and if it's not, show the submit view.

**Comment by EricBAndrews** [comment]
Feels like we can roll this into the 1.1 backend stuff

**Comment by tht7** [comment]
I was getting there with the Deep-linking

I also wanna make an "open in Mlem" Safari extension like Apollo had (fun fact I did it already for Apollo as well XD https://www.reddit.com/r/apolloapp/comments/o916wv/the_new_safari_extensions_on_ios_are_super_cool/
)

**Comment by Sjmarf** [comment]
Duplicate of #24?
