### ISSUE TITLE
Unable to Create New Post

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1372]
**Describe the bug**
When I tap on the New Post button from a community, nothing happens. I am unable to create post. 

**Expected Behavior**
When tapping the New Post button, I would expect to be shown the New Post sheet. 

**Actual Behavior**
Nothing. 

**Mlem Information:**
2.0 (78)

**Comment by Sjmarf** [comment]
I can't reproduce this issue at the moment 🤔 Does this happen in a specific community, or any community? If you restart the app, does the issue persist? Are you using an iPhone or iPad?

**Comment by d42ohpaz** [comment]
> I can't reproduce this issue at the moment 🤔 Does this happen in a specific community, or any community? If you restart the app, does the issue persist? Are you using an iPhone or iPad?

This is happening in any community on any instance. I have tried random communities from All, and a few communities from my subscribe list. If it matters, I'm a lemmy.world user. 

I have also deleted and reinstalled the app. It's not a settings issue because I cannot import my old settings (I'll open a separate issue for that), so right now I'm using the default settings. 

I am using an iPhone 12 Pro Max (MG923LL/A) on iOS 18.0 (22A3354).

**Comment by Sjmarf** [comment]
Thanks for the info! We've just released a new build to the TestFlight; could you let us know if you still experience the issue after updating?

**Comment by d42ohpaz** [comment]
I was able to post in the latest version of the app. Thank you!

**Comment by Sjmarf** [comment]
I'm glad it's working 😄 We must have fixed it at some point accidentally
