### ISSUE TITLE
Clear Cache Button in Settings > Advanced Does Not work

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1394]
**Describe the bug**
When tapping the Clear Cache button under Settings > Advanced, nothing happens. 

**Expected Behavior**
The cache to be cleared. 

**Actual Behavior**
Nothing. 

**Mlem Information:**
2.0 (104)

**Comment by EricBAndrews** [comment]
This looks like a visual bug--relaunching the app shows the updated cache size. We should add a toast and manually re-query the cache to update the display.

**Comment by d42ohpaz** [comment]
> This looks like a visual bug--relaunching the app shows the updated cache size. We should add a toast and manually re-query the cache to update the display.

Confirmed you are correct.
