### ISSUE TITLE
* logging into different instances; receive confirmation that the login is successful; then receive the attached image, indicating the initial load failed; tried uninstalling, application and reinstalling with same result.

### ISSUE THREAD

**Issue by miles202** [mlemgroup/mlem#14]
![image](https://github.com/mlemgroup/mlem/assets/286460/4e3c30b7-504d-4ca8-bdd7-787796907dee)

**Comment by EricBAndrews** [comment]
Closing; we've completely overhauled our login backend, so this shouldn't happen. Please reopen if issue persists.
