### ISSUE TITLE
* opening links on ipad does not respect 'open in app setting

### ISSUE THREAD

**Issue by nocturne213** [mlemgroup/mlem#1406]
**Describe the bug**
What did you do to trigger the bug?
Opening a link

**Expected Behavior**
What did you expect to happen?
I expected the link to open in app

**Actual Behavior**
What actually happened?
The link was opened in Safari

**To Reproduce**
What steps do I need to take to trigger the bug?
Open a link on ipad

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug
2.0 (104) this has been happening since the release of 2.0

**Additional Context**
Any other relevant information
If you go into settings and toggle from open in app to default browser and back again it will work again for a time before going back to opening in default browser.

**Comment by Sjmarf** [comment]
This bug only appears to happen when opening a link from expanded post view; it doesn't happen when opening link from feed
