### ISSUE TITLE
App crashes when loading posts with comments

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1433]
**Describe the bug**
Scrolling the All feed, and tapping into posts. 

**Expected Behavior**
All posts comments load without crashing. 

**Actual Behavior**
The post content loads, but after a short delay the app may crash before it loads/displays the comments. 

**To Reproduce**
Nothing special. Tap into posts with comments. 

**Mlem Information:**
2.0 (129)

**Additional Context**
I use lemmy.world (`0.19.3-6-g86e4cb214`). I have also filed a couple of crash reports through TestFlight. 

Some posts that I found that cause the crash:

- https://midwest.social/post/19172852 (`0.19.5`)
- https://slrpnk.net/post/15122292 (`0.19.6`)
- https://slrpnk.net/post/15122402 (`0.19.6`)

Also, revisiting the posts loads everything as expected. I've tried clearing the cache and restarting the app.

**Comment by Sjmarf** [comment]
I possibly fixed this by adding an extra `@MainActor` in #1430; we'll see if it goes away once that's merged

**Comment by d42ohpaz** [comment]
So far so good with 138. I haven't had a crash all day.

**Comment by Sjmarf** [comment]
I think this is fixed; I haven't seen this particular crash for a while
