### ISSUE TITLE
Make the app language-aware

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#145]
Lemmy provides a lot of ways to specify an instance's discussion languages, a way for users to filter languages, and language tags for every comment or post, we should definitely take advantage of this.

**Comment by ShadowJonathan** [comment]
FWIW this is different from #41, which is about the *language of the app's UI*, this is about showing markers such as "this post is in english", or "this post is in spanish", or allowing someone to pick and choose languages in the submission of comments.

Filtering on language is also included in this, this is an account-wide preference on Lemmy's side, so we should expose it.

**Comment by Sjmarf** [comment]
I split this into #1481, #1200, #1480
