### ISSUE TITLE
Mlem couldn't fetch your account's information. File a bug report.

### ISSUE THREAD

**Issue by ace510** [mlemgroup/mlem#1463]
**Describe the bug**
bug happens when I attempt to add a new account to Mlem

**Expected Behavior**
account is added

**Actual Behavior**
I get the attached error message

**To Reproduce**
add an account to Mlem

**Mlem Information:**
Mlem 1.3.7 (80)

**Additional Context**
screenshot of error attached
![mlem_error](https://github.com/user-attachments/assets/45809395-6021-4ece-bf92-61a593a912dc)

**Comment by Sjmarf** [comment]
Try using your Lemmy username instead of your email? I don't think it accepts emails. We'll make this error clearer in a future version.

**Comment by ace510** [comment]
that worked a treat! thank you!
