### ISSUE TITLE
Crash viewing any post with comments on Lemmy 0.16.7

### ISSUE THREAD

**Issue by mdesmedt** [mlemgroup/mlem#149]
**Describe the bug**
Opening any post -with comments- on a 0.16.7 Lemmy instance always crashes the app. Viewing posts without comments works.

**Expected Behavior**
No crash

**Actual Behavior**
Crash

**To Reproduce**
Log in to an instance running Lemmy 0.16.7 (unfortunately the most up to date supported version on the otherwise excellent YunoHost platform). Then tap on any post with more than 0 comments. The app sometimes shows "Loading comments" then crashes.

**Mlem Information:**
0.0.6 (22)

**Comment by EricBAndrews** [comment]
Under discussion: how do we want to handle API version disparities?

**Comment by EricBAndrews** [comment]
Stale because wow that hasn't been a relevant Lemmy version in a while lol
