### ISSUE TITLE
Crash When Opening Post

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1501]
**Describe the bug**
Tap on post to view comments, and the app crashes. 

**Expected Behavior**
Load the post and view the comments. 

**Actual Behavior**
App crashed. 

**To Reproduce**
It's random. 

**Mlem Information:**
2.0 (169)

**Additional Context**
I submitted a crash report from the email dohpaz at gmail around 10pm EDT.

**Comment by Sjmarf** [comment]
Thanks! This should be fixed [here](https://github.com/mlemgroup/MlemMiddleware/pull/79).
