### ISSUE TITLE
GetPersonDetailsRequest only looks for local usernames

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#154]
Something I discovered while looking at the GetPersonDetailsRequest:

https://github.com/buresdv/Mlem/blob/a9d7526cd07ff669919239081640bf764b9ca2f4/Mlem/API/Requests/GetPersonDetailsRequest.swift#L37-L42

Lemmy accepts bare usernames or usernames with instances, but I think locking us into this pattern is bad. We should be able to query for full usernames across instances, else people aren't even able to find another person, even if they paste the full username.

I get it for the sake of simplicity (#79), but I think that doing this at the API layer is a fallacy, so we should do it a layer above.

**Comment by EricBAndrews** [comment]
Putting this down as a 1.1 issue--feels like something that should be handled at the middleware level

**Comment by EricBAndrews** [comment]
Closing as not planned. Issue is not clear regarding the intended missing functionality. We currently are able to search and access uses from any federated instance.
