### ISSUE TITLE
App crashes when node restarts

### ISSUE THREAD

**Issue by torphexi** [mlemgroup/mlem#155]
App appears to crash when node restarts.

**Expected Behavior**
Error message, something like node currently not available , retry?

**Actual Behavior**
App crash

**To Reproduce**
Most likely restart the node the account is linked with, cannot tell 100% as i dont host my own node.

**Mlem Information:**
0.0.6 (22)
If this started happening recently, write which version introduced the bug

PS:
Thanks for all the hard work everyone, the app looks pretty good :)

**Comment by EricBAndrews** [comment]
Closing as stale since this issue is *ancient* and we've almost certainly reworked whatever code was originally causing it
