### ISSUE TITLE
Create different versioned Mlem Test servers

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#158]
The current mlem test server we have is 0.17.3, but I should deploy additional versions alongside, where we can test a range of versions.

I want at least;
- A 0.16.* server
- A 0.17.* server
- A 0.18.* server

**Comment by ShadowJonathan** [comment]
We should hook #152 and #153 into this, have them login to these servers and do their things, to make sure we dont break things.

**Comment by ShadowJonathan** [comment]
We can also hook #113 into this, where we basically "stamp" and make sure we do support these versions explicitly, and keep testing for them.

**Comment by WestonHanners** [comment]
Any way we could get a docker setup going so we can mess with it locally?

**Comment by ShadowJonathan** [comment]
Not sure, I don't know how rich xcode/swift's testing framework is, wrt setting up stuff and tearing it down

**Comment by EricBAndrews** [comment]
Closing this for now, running locally against different tags has been working well enough. Happy to reopen if somebody wants to pick this up.
