### ISSUE TITLE
Scrolling inadvertently triggers swipe action

### ISSUE THREAD

**Issue by 100000BC** [mlemgroup/mlem#16]
**Mlem Information:**
While scrolling, the swipe function is briefly activated on posts and comments, moving them under your thumb as you scroll. Recommend increasing tolerance for swipe detection.

Has been happening since swipe to vote was added. Still present in build 31.

https://github.com/mormaer/Mlem/assets/67931296/eccc29c3-f3f1-445b-8ae5-52978d268369

**Comment by ShadowJonathan** [comment]
Dont you mean build 30?

**Comment by ShadowJonathan** [comment]
IMO; Scrolling should lock out swipe actions, and vice versa, I remember this being in an older build, even though I can't find the relevant issue right now.

**Comment by yoav-lavi** [comment]
I was just going to post this, happens to me regularly where I scroll and a post will "wobble" due to the scroll being partially on the X axis. I agree that there should be a tolerance (Beta 30)

**Comment by EricBAndrews** [comment]
Seems to be resolved as of #315
