### ISSUE TITLE
Adjust the app for mass adoption (opt-in "Power Mode")

### ISSUE THREAD

**Issue by buresdv** [mlemgroup/mlem#160]
General audiences have expectations of how their apps should function. As it is now, Mlem is more focused on the power users.

In this issue, we will be tracking all features that have to be adjusted in order for the app to appeal to the masses.

- [x] mlemgroup/mormaer-mlem#57

**Comment by ShadowJonathan** [comment]
FWIW this issue is considered to be way deep in the backlog for now, we might not get to it for a little while.

**Comment by EricBAndrews** [comment]
Not planned--this does not align with the current design vision.
