### ISSUE TITLE
* Can't log in

### ISSUE THREAD

**Issue by localjo** [mlemgroup/mlem#164]
**Describe the bug**
What did you do to trigger the bug?

Enter username and password 

**Expected Behavior**
What did you expect to happen?

Should log in

**Actual Behavior**
What actually happened?

"Mlem couldn't fetch you account's information.
File a bug report."

**To Reproduce**
What steps do I need to take to trigger the bug?

Try to log in with any account on any instance.

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug

Version 0.1.0 (30)

**Additional Context**
Any other relevant information

**Comment by localjo** [comment]
Still can't log in with the latest version. I've tried with several instances and accounts.

**Comment by DerpyPlayz18** [comment]
I’m having the same problem on an account on the lemm.ee instance

**Comment by DerpyPlayz18** [comment]
I had the same issue and fixed it by logging in with my username instead of the email address

**Comment by localjo** [comment]
Ah, the confusing part of this is that the Lemmy web interface doesn't call it a username, it calls it a "Display name", and my display name is very generic so I didn't believe it was being used as a unique username. But logging in with it seems to work.
