### ISSUE TITLE
Cannot log in after the last update

### ISSUE THREAD

**Issue by ddnomad** [mlemgroup/mlem#17]
**Describe the bug**
Once the Test Flight update rolled out, the app lost an ability to load any posts / comments / content from both Lemmy instances I was logged into. Logging out / reinstalling the app does not help.

**Expected Behavior**
The app works as intended. 

**Actual Behavior**
The app is unable to log in and fetch content from at least 2 Lemmy instances(https://lemmy.world and https://infosec.pub). 

**To Reproduce**
Unclear in general case, but on my phone it is sufficient to attempt to log in to https://infosec.pub to see an error similar to ![this](https://github.com/buresdv/Mlem/assets/6703766/93da8948-dba9-4a5c-8cd2-f804833690fc) screenshot.

**Mlem Information:**
Version `0.0.7 (23)` introduced the big for me. 

**Additional Context**
Do let me know if there's any other information I can provide.

**Comment by lmkra** [comment]
For me it doesn't work even when using username.

When running Mlem inside XCode Simulator, the last reported error message is:
`getUserId Error info: Unable to decode: <valid-json-object-here>`

I've checked json object reported in the message using jsonlint, but it didn't raise any errors.
Could it be that some info included in user profile is causing JSONDecoder to fail deserialization ?

**Comment by EricBAndrews** [comment]
Closing as stale, login has been reworked significantly since issue was raised
