### ISSUE TITLE
Swipe Gesture on Icon-Tray for forward and backward navigation.

### ISSUE THREAD

**Issue by J0hnny007** [mlemgroup/mlem#172]
Like the title says, I would like to be able to navigate the app with the swiping gesture on the Icon-Tray much like it used to work in Apollo.

**Comment by ShadowJonathan** [comment]
I haven't used this swiping gesture, could you explain it a little more? Where would you start swiping, and/or where would you end the swipe, to perform what kind of navigation action?

**Comment by J0hnny007** [comment]
Well it mostly works like apples App Switcher. For example, if you are currently inside a comment thread and want to move back to the feed you would swipe (to the right) with you thumb on the Icon tray (I think the top bar had this functionality as well). If you want to get back to the comments you would swipe back (to the left). I think you have something like that already implemented with swiping from the sides.

**Comment by ShadowJonathan** [comment]
Ooooh, I wasn't aware that this also worked with the icon tray.

Let me make an adjacent issue, the issue of swiping forwards, and then link it back, thank you for clarifying!

**Comment by ShadowJonathan** [comment]
Related issue: https://github.com/mlemgroup/mlem/issues/174

**Comment by J0hnny007** [comment]
No problem. Btw love the App.

**Comment by BrooklynMan** [comment]
incidentally, an alternative *also* used in Apollo was to simply tap on the Tab icons to navigate backwards one view in that context in case swiping the tab bar was too frustrating due to the task switcher/Home Bar

**Comment by J0hnny007** [comment]
I think this is related to #130.
