### ISSUE TITLE
Investigate: Do not assume usernameOrEmail is username in tryToAddAccount

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#18]
Shoot-off from https://github.com/mormaer/Mlem/issues/290, on [this line](https://github.com/mormaer/Mlem/blob/c3a4d7a885bb54b702efce241fd61d01d2bc664d/Mlem/Views/Tabs/Posts/Components/Post/Components/Instance%20and%20Community%20List/Add%20Account%20View.swift#L224C27-L224C42), we should investigate if this is causing https://github.com/mormaer/Mlem/issues/290 and https://github.com/mormaer/Mlem/issues/188, as all TFF i've seen up until this point of mlemgroup/mlem#17 were using email as login.

**Comment by EricBAndrews** [comment]
Fixed in 2.0
