### ISSUE TITLE
Why are we saving access tokens to JSON? Potential security issue?

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#199]
Currently, Mlem saves account access tokens in a JSON file (`Saved Accounts.json` under Mlem's application support folder) in addition to in the keychain. Doesn't that defeat the whole point of using the keychain? It seems like a security issue to me.

It's pretty easy to just exclude the `accessToken` attribute from the `SavedAccount` codable, which would fix this issue. https://stackoverflow.com/questions/44655562/how-to-exclude-properties-from-swift-codable

**Comment by mormaer** [comment]
Thanks for raising this - the writing to/from disk at start-up needs a bit of love, but that was an issue and needed resolved 🙈
