### ISSUE TITLE
* 

### ISSUE THREAD

**Issue by Benetos** [mlemgroup/mlem#200]
**Describe the bug**
Attempting to build the app in Xcode and it is throwing an error.

**Expected Behavior**
I have tried to download or clone the repo several times as well as going off of the last tag of 0.7 and I keep getting the same error.

**Actual Behavior**
Build fails and produces an error anywhere that the code for defer is use.

` defer
                                                    {
                                                        newPostTitle = ""
                                                        newPostURL = ""
                                                        newPostBody = ""
                                                        newPostIsNSFW = false
                                                        isPostingPost = false
                                                        focusedNewPostField = nil
                                                    }`

**To Reproduce**
Unknown if it is an issue with my Xcode or with the repo. If it is with the repo simply download or clone it as it is right now or tag 0.7 and it should give the same error.

**Mlem Information:**
Version + Build number
Current and 0.0.7

**Additional Context**
Error Code: Main actor-isolated property 'newPostTitle' can not be mutated from the main actor

**Comment by Sjmarf** [comment]
Yeah I had this issue too. Someone told me it was because I'm on a different Xcode/Swift version or something. I just commented the code out and it builds fine

**Comment by EricBAndrews** [comment]
This is usually solved by upgrading to the latest Xcode.

**Comment by Sjmarf** [comment]
I'm on the latest beta and it works fine now.
