### ISSUE TITLE
Ensure we handle invalid tokens

### ISSUE THREAD

**Issue by mormaer** [mlemgroup/mlem#207]
## Introduction
As of now the application stores the users authentication token after successful login. This is then re-used in future sessions for accessing the API.

Although so far the tokens appear to be long-lived, there will/should be scenarios where the token becomes invalid. At this point we currently have no way to notify the user that the session is invalid and/or offer to log in again.

## Requirements
If the API was to return an unauthorised error when we attempt to use the token we have stored, we should gracefully handle that scenario by attempting to silently login again and/or prompt the user.

**Comment by mormaer** [comment]
I was thinking about this, and I believe in order to correctly handle this scenario when it comes around we will need to make some changes to how we currently handle accounts.

At present after login we store the token in the keychain, but should the session be invalidated by the server (or the user if an option such as _sign out from all sessions_ becomes available via Lemmy) we have no way to recover, other than to ask the user to sign in again from scratch.

A more robust approach would be for us to securely store the users credentials in the keychain so that we can make a login call as required to create a new session, as these changes would likely mean existing accounts would need replaced (the model would need to change) I believe this is something that should be addressed ASAP.

**Comment by d42ohpaz** [comment]
FYI, there are no errors or notices that you are logged out when a session becomes invalid. Instead, the only noticeable things that happens is your Subscribed feed is empty, and you cannot interact (i.e., upvote or downvote). It's confusing, and can easily be dismissed as server issues when in fact it's not a server issue.
