### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by MarioBarisa** [mlemgroup/mlem#209]
**Describe the bug**
I tried to log in

**Expected Behavior**
me loging in

**Actual Behavior**
mlem gives an error " Mlem couldnt fetch you accounts information. File a bug report" 

**To Reproduce**
Try to log in on Vlemmy.net instance

**Mlem Information:**
version 0.1.0 ( 30 )

**Additional Context**
check the attached files for a video

https://github.com/mlemgroup/mlem/assets/130148782/c9994903-00ba-4722-90b4-f761d2c0fcb0

**Comment by postthought** [comment]
Facing a similar issue for all the instances I have an account on. Lemmy.ml or Lemmy.dbzer0.com or beehar.org. Can’t login to any of these

**Comment by nikolaosginos** [comment]
Seems to work when you use your username instead of your email address. Funnily, I only got this idea because I tried a different Lemmy app and also used my mail address. This other Lemmy app then specifically told me to try my username instead. That worked there and it also worked on Mlem.

**Comment by EricBAndrews** [comment]
Closing as stale, we've reworked login significantly since this issue was raised
