### ISSUE TITLE
Blocking Communities Should Remove Posts from Feed

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#215]
## Introduction
Currently in 0.10 (30), when you open a community and block it, returning to your feed still shows the post(s) from the community you just blocked. 

## Requirements
After blocking a community and returning to your feed, the posts from the blocked community should automatically be filtered out.

## Discussion
If possible, removing posts from the feed should not affect your place in the feed (ie your scroll position should not be reset).

**Comment by EricBAndrews** [comment]
Should be a minor change, slating for 1.1

**Comment by EricBAndrews** [comment]
Closed a while back, forget the PR
