### ISSUE TITLE
Unread inbox badge counter in-app

### ISSUE THREAD

**Issue by JakeShirley** [mlemgroup/mlem#217]
## Introduction
We should be able to, at a glance, see unread notifications.

## Requirements
Your inbox icon on the bottom tab bar should have a number to indicate how many unread notifications you have.

## Discussion
In the future we could add app badges as well (on the iOS springboard) but we need settings to tweak/turn off as people have _very_ strong opinions on the matter.

## What I Need
Gimme them unread counts!

**Comment by EricBAndrews** [comment]
Bumping back to 1.1. Non-critical, we gotta ⛴️

**Comment by EricBAndrews** [comment]
Taking @JakeShirley off this issue because I have the feeling he's not getting to it any time soon :P
