### ISSUE TITLE
Quick-comment UI element has disapeared

### ISSUE THREAD

**Issue by JakeShirley** [mlemgroup/mlem#218]
**Describe the bug**
The text box that is normally present at the bottom of the screen when viewing a post thread is no longer there.  As far as I can tell the only way to comment is by clicking the context menu and clicking "reply"

**Expected Behavior**
It should be easy to reply to posts

**Actual Behavior**
Replying to threads is locked behind a context menu

**To Reproduce**
Go to a thread and try to reply.

**Mlem Information:**
30

**Additional Context**
n/a

**Comment by EricBAndrews** [comment]
Resolved in #214 and #219
