### ISSUE TITLE
Example posts causing poor scrolling performance - v0.1.0(19)

### ISSUE THREAD

**Issue by dtackgrounded** [mlemgroup/mlem#22]
## Introduction
This is to help identify and improve poor feed scrolling performance. Sometimes while viewing the feed, scrolling will become jittery and skip unpredictably while viewing certain types of posts.

## Requirements
Go to the community where these posts are from, presents multiple examples of the problem - yt_tech.

## Discussion
Please find the attached video of examples of posts that cause jittery scrolling in the feed; TLDR posts from the yt_tech community are one repeatable example of posts that cause this problem.

## What I Need

https://github.com/mormaer/Mlem/assets/867563/78b456f8-f5ac-4ace-bd3b-48d337d8f375

**Comment by EricBAndrews** [comment]
Marking as closed, but optimization is always open :)
