### ISSUE TITLE
* Unable to submit post unless I include a URL

### ISSUE THREAD

**Issue by duetschlandftw** [mlemgroup/mlem#221]
**Describe the bug**
When filling out the fields for a text post, I left URL blank, but was unable to submit my post until I populated it

**Expected Behavior**
Expected post to submit on hitting submit button

**Actual Behavior**
I was given the error "Submit Failed, you seem to have entered an invalid URL, please check it again"

**To Reproduce**
Attempt to submit a text post on Lemmy.world/c/fediverse

**Mlem Information:**
Version + Build number: Latest

**Additional Context**
I was able to edit the link out on lemm.ee after posting

**Comment by EricBAndrews** [comment]
Fixed somewhere along the line--I can't find the PR but it works on the current master build
