### ISSUE TITLE
Inbox Should Have Unread Tab for Unread Messages

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#227]
## Introduction
The Lemmy website provides a tab to show all unread messages, in addition to a tab to view all messages regardless of their read status.

## Requirements
Add a view that will show only unread messages in the Inbox tab.

## Discussion
Another point would be when marking an unread message as read, it should be removed from the Unread tab once the server acknowledges the message as now read. 

## What I Need
A way to view only unread messages; and a winning lottery ticket.

**Comment by EricBAndrews** [comment]
Moving to Discussion to draft UI ideas.

Possibly just a "show/hide read" toggle?

**Comment by d42ohpaz** [comment]
I was envisioning something similar to the Lemmy-UI where there would be a separate and distinct tab bar to toggle between unread and all. 

![Image](https://github.com/mlemgroup/mlem/assets/2528463/71377ac0-bb73-4d34-913e-3e124f70dce7)

Another suggestion would be to mimic what Reddit does, and simply add a new tab to the existing tab bar for unread messages.

![Image](https://github.com/mlemgroup/mlem/assets/2528463/778b37d4-c7a9-47c9-a192-a512a8160829)

I have no strong feelings one way or the other, so either (or another) solution works for me. My concern is only to distinguish unread messages from their counterparts.

**Comment by Sjmarf** [comment]
I don't think adding *another* tab is good UX design, especially when the user might want to filter by 'unread replies' or something like that. I'm in favour of having a separate toggle for unread messages.

**Comment by EricBAndrews** [comment]
We could do something like what ProtonMail does:
![image](https://github.com/mlemgroup/mlem/assets/44140166/8a696f0f-716f-431f-b8e2-9c813f266454)
