### ISSUE TITLE
Tab bar is transparent when returning from Safari

### ISSUE THREAD

**Issue by mormaer** [mlemgroup/mlem#231]
**Describe the bug**
When returning from viewing a page via Safari the tab bar in the application is momentarily transparent, causing a small visual glitch.

**Expected Behavior**
The tab bar should not be transparent when returning to the application.

**Actual Behavior**
For a brief moment the tab bar is transparent, see this video for an example:

https://github.com/mlemgroup/mlem/assets/5231793/d47e7ae2-729d-487f-9de9-daff1aaffecb

**To Reproduce**
- Tap on a link within the application which navigates to Safari
- Return to the application
- Observe the tab bar is transparent for a brief moment

**Mlem Information:**
0.1.0 (121)

**Additional Context**
The route cause is unclear but we may want to try avoiding pushing Safari from `UIKit`,  some of the commits on this previous PR (https://github.com/mlemgroup/mormaer-mlem/pull/46) show an example of presenting Safari from within the `SwiftUI` context which is worth testing to see if using an approach like that may help solve this issue.

**Comment by boscojwho** [comment]
Could not reproduce this using TestFlight beta version 1.0.0 (213) on iPhone 13 mini running iOS 16.5.1 (c).

Steps Attempted:
- Fresh launch of app into Feed tab.
- Tap on web link to open Safari view.
- Optionally, scroll down to make navigation bar/toolbar hide then show again.
- Tap "Done" to go back to Feed (or swipe to go back).

**Comment by Sjmarf** [comment]
Theoretically this shouldn't be a problem anymore, since we're using a completely custom tab bar.
