### ISSUE TITLE
The default Mlem icon is rendered differently to the others in Settings

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#236]
I'm not sure if this is limited to just the settings menu, or if it also applies to the actual icon. Maybe someone edited the icon and resaved it in a slightly different format or something?

![image](https://github.com/mlemgroup/mlem/assets/78750526/1a449a4e-a20b-416d-bbc2-5ceb60f3d2fb)

**Comment by EricBAndrews** [comment]
That's a sharp eye you've got! The icon was edited to make it brighter, and in the process we lost a tiny bit of resolution. Our icon designer has gone AWOL, though, so until we find him this'll have to do

**Comment by acdoe98** [comment]
Also all the icons have “By Clay/s” when Mlem Dark has “By ClayS” without the forward slash. 😏

**Comment by mlsteiner** [comment]
Hi @EricBAndrews, wondering if there any interest in having other designers contribute alternative icons to the project?

**Comment by tht7** [comment]
Can we just open for community contributions on this one? Like invite people from the community to contribute icons

**Comment by EricBAndrews** [comment]
@mlsteiner we'd love that! We're still working out what the exact process is going to be for that, but if you've got some ideas please hop into our [matrix chat](https://matrix.to/#/#mlem-general:matrix.org) and we'll talk!
