### ISSUE TITLE
Trailing slash in instance URL not handled properly.

### ISSUE THREAD

**Issue by JiimBob** [mlemgroup/mlem#239]
**Describe the bug**
When adding an account, if the user inputs a homepage with a trailing slash the account fails to add.

**Expected Behavior**
Account should be added

**Actual Behavior**
Looking up the API endpoint fails to locate the proper schema, account fails in adding.

![Screenshot from simulator showing an error message stating could not connect to https://test-mlem.jo.wtf/](https://github.com/mlemgroup/mlem/assets/44332255/c165cb13-3b3c-4b1c-89ff-3840c5ec3fc6)

**To Reproduce**
Attempt to add a valid account from an instance, but leave a trailing slash in the URL field ie: https://test-mlem.jo.wtf/

**Mlem Information:**
Version + Build number
Tested on 0.1.0

**Additional Context**
From console during the account add:
```
https://test-mlem.jo.wtf//api/v3/user is invalid
https://test-mlem.jo.wtf//api/v2/user is invalid
https://test-mlem.jo.wtf//api/v1/user is invalid
http://test-mlem.jo.wtf//api/v3/user is invalid
http://test-mlem.jo.wtf//api/v2/user is invalid
http://test-mlem.jo.wtf//api/v1/user is invalid
Will start the account addition process
Sanitized link: test-mlem.jo.wtf/
https://test-mlem.jo.wtf//api/v3/user is invalid
https://test-mlem.jo.wtf//api/v2/user is invalid
https://test-mlem.jo.wtf//api/v1/user is invalid
http://test-mlem.jo.wtf//api/v3/user is invalid
http://test-mlem.jo.wtf//api/v2/user is invalid
http://test-mlem.jo.wtf//api/v1/user is invalid
```

**Comment by JiimBob** [comment]
Likely covered under #83 but I didn't see it explicitly mentioned.

**Comment by Sjmarf** [comment]
Closing as duplicate of #83
