### ISSUE TITLE
IPA in release tab for TrollStore / sideload users

### ISSUE THREAD

**Issue by ComeOnBear** [mlemgroup/mlem#25]
## Requirements
Have a compiled version of the app in the .ipa format so users on TrollStore compatible versions, Jailbroken users, and Altstore users can enjoy the app without taking up TestFlight spaces 

## What I Need
What I need it to do
Have a functional compiled .ipa version of the app (ideally in the releases tab), this doesn’t need to contain the minor updates, just major ones ideally. I’m sure others will agree with me here as TestFlight sucks on my phone (and doesn’t even let me use it)

**Comment by Sjmarf** [comment]
Is this still needed now that Mlem is on the App Store? I believe this issue was created when we had a full TestFlight, in which case loading the `.ipa` directly would have been useful. I'm going to tentatively close this for now - if someone still wants this, let me know and I'll reopen it.
