### ISSUE TITLE
Images in Settings

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#253]
Some settings could benefit from having graphics that more effectively communicate what the setting does. 

Most in need of something like this is the 'vote complex style' setting (which we've already seen people confused about).

Similarly, the 'Post Size' setting could have simplified graphics showing what each view type looks like. This saves the user from having to go back to the main feed tab each time, if they don't know that the setting can be changed within the feed menu itself. 

Additionally, Post and Comment appearance settings could have preview graphics that adapt when you toggle settings on/off, as we have already with the website preview customisation settings. 

I'd be happy to work on this one along with the other Settings-improvement issues (#248, #51, #50) if they get approved.

**Comment by EricBAndrews** [comment]
Preview graphics will alleviate a ton of this--closing this, opening issues for post and comment previews in settings, and handing those to you since you've got some great work done on that front already

**Comment by EricBAndrews** [comment]
You'll have to comment on them, though--#303 and #304, for your convenience
