### ISSUE TITLE
Allow editing accounts 

### ISSUE THREAD

**Issue by phareous** [mlemgroup/mlem#262]
Provide the ability to edit an account to reenter credentials

**Comment by phareous** [comment]
That would be fine, it’s just not ideal to have to delete the entire account and readd it

**Comment by Sjmarf** [comment]
We store the user's username, so we can autofill that when we prompt them to re-enter their password.

**Comment by phareous** [comment]
If the reauthentication prompt works, then maybe editing isn't needed. I was mainly trying to use it to reauthenticate when the acct in the app was hosed

**Comment by EricBAndrews** [comment]
Closing as stale per #270 and #261
