### ISSUE TITLE
Allow post thumbnail in compact (and other) views to open post content

### ISSUE THREAD

**Issue by raptormama** [mlemgroup/mlem#279]
Currently, when tapping on a compass icon on a link post, Mlem opens the post and the URL has to be tapped from there to view the link. (The URL is also very small and often difficult to tap). Tapping the thumbnail on an image post opens the post with the image, but the image cannot be interacted with.

Tapping on the thumbnail of a URL post should open that URL (either in the in-app browser or in the default browser/selected browser, as per preferences) and tapping an image thumbnail should open just the image, with a 3D press/long press opening a context menu (other issues have been raised regarding image handling; tapping the thumbnail should activate whatever system is implemented).

Tapping the post title should open the post as is currently done.

**Comment by EricBAndrews** [comment]
Related to #31
