### ISSUE TITLE
Observation: buttons too clustered, or too many

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#28]
![image](https://github.com/mormaer/Mlem/assets/22740616/081f05bf-058d-42db-93b3-16485657351b)

---

![image](https://github.com/mormaer/Mlem/assets/22740616/c1e1c8ad-e195-452d-99fc-ef43a9ad8dca)

---

This is something I've noticed while using the app, I find the buttons a bit too overwhelming or clustered, could we possibly move some to the pea menu, or increase the margins/padding around the buttons, and/or make them bigger?

Also, the low "chin" of posts makes it personally hard to tap to go to the post, as it doesn't give much surface area to comfortably try to aim.

**Comment by EricBAndrews** [comment]
Closing because we un-clustered the buttons in #219
