### ISSUE TITLE
"Image failed to load" placeholder should be taller

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#280]
![image](https://github.com/mlemgroup/mlem/assets/78750526/a3037734-3b09-4113-9a41-35a22cb60798)

**Comment by Sjmarf** [comment]
Another post:

![image](https://github.com/mlemgroup/mlem/assets/78750526/5dbb7a3e-49a5-40ac-b050-ff9f0c263469)

A comment (presumably with an image):

![image](https://github.com/mlemgroup/mlem/assets/78750526/d067a7fb-ecd7-405c-bc17-8d145ca3b6b2)

**Comment by EricBAndrews** [comment]
Closed in #394
