### ISSUE TITLE
Error graphic on top of comment text

### ISSUE THREAD

**Issue by Rexios80** [mlemgroup/mlem#281]
**Describe the bug**
Error graphic on top of comment text

**Expected Behavior**
Don't show the error on top of content that's loaded successfully. If there is an error loading part of the content, show the error in-line instead of on top.

**Actual Behavior**
Error shows on top of comment text

**To Reproduce**
Open this comment https://toad.work/comment/437672
It appears to have an inline gif

**Mlem Information:**
1.0.0 (213)

**Additional Context**

![IMG_1959](https://github.com/mlemgroup/mlem/assets/7896519/8ae2349b-272f-4d8c-baca-9880cccb71a4)

**Comment by Sjmarf** [comment]
#280

**Comment by EricBAndrews** [comment]
The error graphic generally is super jank, needs to be cleaned up
