### ISSUE TITLE
I would like to be able to customize the label under the profile icon, and

### ISSUE THREAD

**Issue by rubythulhu** [mlemgroup/mlem#289]
## Introduction
I have accounts with the same username on multiple instances. I can't easily tell what account i am on. 

## Requirements
allow, for each account, and to be configured globally, with the following options:

* use username as label
* use instance as label
* use username@instance (or username \n instance?)
* use a custom label

## Discussion
I feel like the above is a good enough description, but also i would love it if i could switch accounts from the profile tab as well.

## What I Need
I would love it if i could tell what account i'm connected to at a glance.

**Comment by EricBAndrews** [comment]
Rolling this into the 1.1 accounts/instances UX update
