### ISSUE TITLE
Rename "All" to "All Known Communities"

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#29]
After seeing [this](https://beehaw.org/post/515673?scrollToComments=true) post, I think it'd be good to clarify that "All" does not mean "All Servers", but "All Known Communities", which is limited by the local server, and all the communities that any local user has subscribed to.

**Comment by BoiLudens** [comment]
![image](https://github.com/mlemgroup/mlem/assets/25911562/f34c81e3-b916-4f2d-9273-d0c39ccdb197)
@ShadowJonathan like this?

**Comment by ShadowJonathan** [comment]
No, change "All Communities" to "Known Communities", and then it'll work

**Comment by BoiLudens** [comment]
![image](https://github.com/mlemgroup/mlem/assets/25911562/7b42b98f-0528-44a1-8ce0-c35180828ae1)
![image](https://github.com/mlemgroup/mlem/assets/25911562/b98561e8-1c12-45ed-b821-11c06767cbd5)
@ShadowJonathan

**Comment by Sjmarf** [comment]
"All Known Communities" would work better imo.

**Comment by ShadowJonathan** [comment]
Known, the problem with "all" is that it reinforces the idea that the local server (or app) is enumerating all communities "on Lemmy", while that isn't the case.

Description is fine, but imo All -> Known.

**Comment by Sjmarf** [comment]
> Known, the problem with "all" is that it reinforces the idea that the local server (or app) is enumerating all communities "on Lemmy", while that isn't the case.
> 
> Description is fine, but imo All -> Known.
> 
> Possibly "All Known" for the feed header would work, yeah.

The reason why I think we should retain the word 'all' is for consistency with Lemmy-ui.

**Comment by ShadowJonathan** [comment]
Ah, in that case i think "All Known" across the board could be better. I was a bit afraid that "All" in this instance would simply shortcut someone into thinking that it is "All", not "All Known"

Sorry for the churn, "All Known" it is.

**Comment by BoiLudens** [comment]
![image](https://github.com/mlemgroup/mlem/assets/25911562/5ae01a97-9987-450e-95c2-5e71f571da5d)
![image](https://github.com/mlemgroup/mlem/assets/25911562/41413247-e343-42bc-8128-1faad70e9a64)
TA-DA!

**Comment by BoiLudens** [comment]
May I be assigned this task, this is my first contribution.

**Comment by EricBAndrews** [comment]
Fixed in #274
