### ISSUE TITLE
NSFW tag toggle in 'new post' sheet doesn't support dark mode

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#290]
Not sure if this is intentional. I'd like to be assigned this task if it's something you think we should change.

![image](https://github.com/mlemgroup/mlem/assets/78750526/c18afd8e-fedc-4180-8645-7c74ac1c9b88)

![image](https://github.com/mlemgroup/mlem/assets/78750526/cd5cbdf9-8df2-41b2-8bcd-155b74982a51)

![image](https://github.com/mlemgroup/mlem/assets/78750526/406a9741-9b7c-4d00-b634-f1840a2d9c62)

![image](https://github.com/mlemgroup/mlem/assets/78750526/090600bd-2fe7-4412-9c04-a16313419193)

**Comment by EricBAndrews** [comment]
Have at it!
