### ISSUE TITLE
Tap images to expand them

### ISSUE THREAD

**Issue by buresdv** [mlemgroup/mlem#31]
## Introduction
As it is now, there is no way to tap on a picture and have it enter full screen.

## Requirements
Add the possibility to tap on a picture to make it fullscreen. It should behave like in Photos, where tapping a picture expands it and then you can move it around and flick it away.

Should look like this: https://streamable.com/8xz0hv. Lemmy doesn't support albums, so there's no need to support more than one picture in a post.

## What I Need
Rework the relevant files containing image views ( [Post Item](https://github.com/buresdv/Mlem/blob/8105184720a51f7bd92e47b5247f11098cc816a9/Mlem/Views/Tabs/Posts/Components/Post/Components/Community%20View/Post%20Item/Post%20Item.swift#L117) ) to support this feature. Also implement mlemgroup/mormaer-mlem#61 to comply with Apple's guidelines around NSFW material.

**Comment by rubythulhu** [comment]
The only thing that makes mlem a sub-par lemmy app to me is that I can't save images, and have to do an awkward `click "..." button` -> `share` -> `copy url` -> `paste into safari` -> `hope that doesn't fail` -> `save image via safari`. 

I just want to save memes :(

**Comment by tht7** [comment]
Working on it man!

https://github.com/mlemgroup/mlem/pull/171

**Comment by EricBAndrews** [comment]
Moving this to "future"--we want to have a nice full-screen image viewer rather than the sheet, but that's a hefty chunk of development and should wait until post-2.0
