### ISSUE TITLE
Need Toasts for Subscribe, Favorite, Unsubscribe, Unfavorite

### ISSUE THREAD

**Issue by WestonHanners** [mlemgroup/mlem#318]
**Describe the bug**
Need someone to go add toasts for these actions
Please see Block Person for implementation details

InteractionSwipeAndMenuHelpers.swift:259

**Comment by jeltebr** [comment]
I would like to try and work on this issue

**Comment by EricBAndrews** [comment]
All yours

**Comment by jeltebr** [comment]
Can the blocking/unblocking of a community be included in this scope? And does this scope only include the community actions?

**Comment by EricBAndrews** [comment]
Yes, it can--in theory, anything that changes important state with no explicit feedback should toast, and it'd be great to get those all done in one go. 

Community:
- Subscribe
- Unsubscribe 
- Favorite
- Unfavorite
- Block
- Unblock

Person:
- Block
- Unblock

That's all I can conjure off the top of my head, please comment if I've forgotten any
