### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by isametry** [mlemgroup/mlem#32]
## Introduction
Right now, after first downloading Mlem, the app just… starts with an empty account list.

For a good first impression and to make it easier to get started, a couple of screens of onboarding would be a useful addition.

## Requirements / Ideas

- Briefly explain what Lemmy is and where to sign up if they haven't already (= most likely send them to https://join-lemmy.org/instances)
- Present the login screen automatically, rather than making the user find the plus button themselves.
- (Besides logging into existing accounts, will there also be an option to sign up for new ones?)
- If the account isn't following any communities, suggest some popular ones? mlemgroup/mlem#86 (but should be skippable for sure)

**Comment by EricBAndrews** [comment]
Closed in #533
