### ISSUE TITLE
* #Days post time display in feeds should be truncated to #d or #D.

### ISSUE THREAD

**Issue by 100000BC** [mlemgroup/mlem#33]
**Describe the bug**
Viewed the main feeds page on beehaw

A post that is two days old or older will have their time stamp display as “2 Days” with “Days” wrapping to an additional line.

It should instead be truncated to just the initial of the days. I assume months will have the same issue, so months should be abbreviated to “M”.

**Comment by ShadowJonathan** [comment]
A note for the future, we shouldn't forget to localise this as well; #41

**Comment by EricBAndrews** [comment]
Status on this?

**Comment by Sjmarf** [comment]
Apologies, I've had exams for a couple of days. I'll do it later today.

**Comment by EricBAndrews** [comment]
No worries! Hope your exams went well

**Comment by Sjmarf** [comment]
To be clear - do you want the "2 Days" to always be truncated to "2d", or only when "2 Days" won't fit?

**Comment by EricBAndrews** [comment]
Always truncate

**Comment by Sjmarf** [comment]
Sure 👍

**Comment by EricBAndrews** [comment]
Fixed in #229
