### ISSUE TITLE
Tab bar moves when keyboard is active

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#344]
![image](https://github.com/mlemgroup/mlem/assets/78750526/8864658b-7841-44c6-8f9f-23f8bd5720c8)

**Comment by WestonHanners** [comment]
I kinda like it.

**Comment by EricBAndrews** [comment]
Related t #342

**Comment by EricBAndrews** [comment]
> I kinda like it.

I also kinda like it but it's also completely wretched
