### ISSUE TITLE
Pressing return in account creation "bobs" modal

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#347]
Using Return to navigate to the next field causes unintended animation. 

https://github.com/mlemgroup/mlem/assets/44140166/0280c4af-7b70-4a29-8289-728f604e7de8

**Comment by WestonHanners** [comment]
Actually looks like an iOS bug where keyboard dismissal is being processed before the onSubmit handler can change focus, causing a short keyboard bounce. the sheet presentation is exacerbating it.

**Comment by Sjmarf** [comment]
I'll look into this one

**Comment by Sjmarf** [comment]
It now only bobs the keyboard, and not the modal. People on some SO posts say that it's a bug in iOS 16. I couldn't find a working solution - it might be possible to fix it by making the menu a basic `Form`, but that's a lot of work and arguably isn't worth it.

**Comment by EricBAndrews** [comment]
I'm going to call this "good enough" and close the issue.
