### ISSUE TITLE
Comment formatting options 

### ISSUE THREAD

**Issue by NathanielIR** [mlemgroup/mlem#390]
When writing text while commenting or even posting, having text format options like bold or italics would be nice. Obviously you can just do it manually but having it in app would be great. And it would be even more useful for more obscure or difficult things which might be hard for non tech savvy people such as formatting images in comments or adding hyperlinks

**Comment by EricBAndrews** [comment]
Child of #62

**Comment by EricBAndrews** [comment]
Implemented with 2.0 markdown support
