### ISSUE TITLE
Add option to disable extra upvote swipe haptics

### ISSUE THREAD

**Issue by Hikiru** [mlemgroup/mlem#393]
It feels like too much to me. It’s a bit distracting. I prefer the simple click from just swiping over upvote, and it feels weird when that stacks on top of the upvote haptics. It’s distracting.

**Comment by EricBAndrews** [comment]
Haptics are getting a major overhaul in the next update (#336)--they're a bit bone-shaking in the current prod build. 

There's follow-up work scheduled for haptics (#319). I've added a note to that issue about partially disabling haptics, closing this issue as dupe. 

Thanks for the feedback!
