### ISSUE TITLE
Add hide post feature

### ISSUE THREAD

**Issue by becausebirds** [mlemgroup/mlem#40]
## Introduction
I frequently like to hide posts in my feed, either stuff I keep seeing, or stuff that I don't want to see but don't want to unfollow a community completely for that one piece of content.

## Requirements
Add the ability to click a ... menu (or something) and hide a post from the feed.

**Comment by EricBAndrews** [comment]
Tentatively flagging for 2.0, would require the local storage architecture as discussed in #962

**Comment by Sjmarf** [comment]
Might be doable in 2.0, yeah. We should consider a more advanced storage architecture than JSON for all of this stuff. Possibly CoreData or some other database system.

**Comment by Sjmarf** [comment]
They've implemented this server-side in 0.19.4
