### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by xabirequejo** [mlemgroup/mlem#41]
Hi 👋 

I'd be interested in localising Mlem.

Is there any file I could have a look at or is it too early for this?

I can use platforms such as Weblate or Transifex, or even pull requests via GitHub, but I am not able to run Xcode — not only because I've got a 10yo Intel laptop but also because my knowledge is limited.

**Comment by einsteinx2** [comment]
I can help with Spanish localization.

**Comment by Sjmarf** [comment]
Duplicate of #146
