### ISSUE TITLE
Comments missing information

### ISSUE THREAD

**Issue by Rexios80** [mlemgroup/mlem#411]
**Describe the bug**
Update the app

**Expected Behavior**
Comments show all the same information they showed before

**Actual Behavior**
Comments no longer show user instance or upvote count 

**To Reproduce**
Update the app to the TestFlight version

**Mlem Information:**
1.0.0 (387)

**Additional Context**
App Store version:
![image](https://github.com/mlemgroup/mlem/assets/7896519/a90a8c9a-3695-4b96-836e-d2735b650300)
TestFlight version:
![image](https://github.com/mlemgroup/mlem/assets/7896519/a6d4bde4-db56-4541-ad75-60d7f2733fe8)

**Comment by Rexios80** [comment]
I have the setting to show user instance enabled in the settings

**Comment by EricBAndrews** [comment]
The upvote count may be due to a recent change in settings defaults that could have overridden existing prefs--what is your "appearance > comments > vote complex style" set to?

**Comment by Rexios80** [comment]
I set it to standard and the count shows up now. If plain is the new default, shouldn't it be on top of the list?

![image](https://github.com/mlemgroup/mlem/assets/7896519/b26aa7a4-ae4f-44df-b1c7-de6b05767ac7)

**Comment by EricBAndrews** [comment]
Yeah, the naming there is admittedly not very good. We've got a snazzy drag-and-drop bar customization system planned/in tentative development by @boscojwho, which should remove the need to name them altogether, but until then we should rename and reorder--somethint like Plain/Classic/Symmetric
