### ISSUE TITLE
Swiping home indicator to exit app causes account switcher modal sheet to appear when reopening app

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#414]
**Describe the bug**
Swiping on home indicator is probably triggering the long press gesture on tab bar that's responsible for showing account quick switcher.
- Bug is not *always* reproducible.
- Sometimes also happens if swipe gesture happens over other tabs on tab bar.

**Expected Behavior**
System home indicator gestures should have a higher priority than account quick switch gesture.

**Actual Behavior**
Account quick switch gesture on tab bar triggers simultaneously with home indicator swipe gesture.

**To Reproduce**
1. Open app.
2. Swipe home indicator to close app (ensure finger swipes over "Account" tab icon.
3. Reopen app.
4. Account quick switcher modal sheet is open.

**Mlem Information:**
1.0.1 (387) and /dev build 1.0.1 (24).

**Additional Context**
Tested on iPhone 13 mini on iOS 16.

**Comment by boscojwho** [comment]
Ah, turns out there is a drag gesture to trigger account switcher on swipe up in tab bar.
- I'm not sure if there should be any swipe/drag gestures in the tab bar area. There's already a scroll view above it, and on home indicator devices, I think there should be room for the home indicator drag gesture to breathe, so to speak.

**Comment by EricBAndrews** [comment]
Hard disagree on removing the gesture for two reasons:

1. Accessibility. When the system font is a11y large, long press on tab bar items opens a HUD to display the item name and icon in large font. This overrides the long press, so the drag up gesture keeps that quick switching action readily available for those users (it's actually super satisfying to drag up from the HUD long press--max out your font size and give it a try!). This is the reason that gesture exists in the first place and account switching isn't on a context menu. 
2. IMO it's way smoother/easier than the long press (which should eventually be a 3D Touch, but even so)--I use it almost exclusively. 

That said, you raise the very salient points that (a) the gesture space might feel crowded and (b) it has an annoying interaction with the home menu. Therefore I propose the following as a resolution to the issue:

1. Add an option under tab bar settings to disable that gesture
2. Figure out some way to dismiss the modal when the app moves into the background

**Comment by boscojwho** [comment]
> 1. Accessibility
- Ah, did not know this was an accessibility feature, makes more sense =) But yes, an option would be very nice because I'm inadvertently opening this menu multiple times everyday, not fun.
- Also might be worth investigating how other apps deal with this in an accessibility context.

> 2. Figure out some way to dismiss the modal when the app moves into the background
- Possibly could monitor for app lifecycle here?

Also, I wonder if this is even more of an issue on Home Button devices? On those devices, there's no safe area between the tab bar and the bottom edge of the screen, and the swipe up system gesture is used to open Control Center.

**Comment by fer0n** [comment]
I also open that constantly by accident, I was wondering where that was coming from.

**Comment by EricBAndrews** [comment]
Marking this as 1.1 because it's a refinement of a 1.1 feature.

Re: how do other apps handle this: of the Lemmy apps with an App Store release, we're the only one that's even thought about this--Memmy doesn't have the accessibility HUD and Liftoff doesn't have the quick switcher to begin with.

As far as other apps out in the wild go, I haven't seen any that overload tab bar functionality except Apollo, which we obviously can't check :(

**Comment by fer0n** [comment]
[Ivory](https://apps.apple.com/de/app/ivory-for-mastodon-by-tapbots/id6444602274?l=en-GB) shows a profile picture on the top left where you can long press. You can also swipe left/right on the navigation bar to switch between your accounts. And there's also a long press on the tab bar to assign different menus (not related to the account switching). 

Maybe a double tap on the profile, or a tab followed by a long press? Navigation bar swipe could also work

**Comment by boscojwho** [comment]
> Marking this as 1.1 because it's a refinement of a 1.1 feature.
> 
> Re: how do other apps handle this: of the Lemmy apps with an App Store release, we're the only one that's even thought about this--Memmy doesn't have the accessibility HUD and Liftoff doesn't have the quick switcher to begin with.
> 
> As far as other apps out in the wild go, I haven't seen any that overload tab bar functionality except Apollo, which we obviously can't check :(

I feel so dumb for not taking a bunch of screenshots/videos of Apollo before it went dark lmao

**Comment by boscojwho** [comment]
> Marking this as 1.1 because it's a refinement of a 1.1 feature.
> 
> Re: how do other apps handle this: of the Lemmy apps with an App Store release, we're the only one that's even thought about this--Memmy doesn't have the accessibility HUD and Liftoff doesn't have the quick switcher to begin with.
> 
> As far as other apps out in the wild go, I haven't seen any that overload tab bar functionality except Apollo, which we obviously can't check :(

It makes me happy that Mlem constantly has accessibility in mind, even with these rapid development cycles =)

**Comment by boscojwho** [comment]
> [Ivory](https://apps.apple.com/de/app/ivory-for-mastodon-by-tapbots/id6444602274?l=en-GB) shows a profile picture on the top left where you can long press. You can also swipe left/right on the navigation bar to switch between your accounts. And there's also a long press on the tab bar to assign different menus (not related to the account switching).
> 
> Maybe a double tap on the profile, or a tab followed by a long press? Navigation bar swipe could also work

Oh very cool, is the swipe on the navigation bar something you can toggle in Ivory's settings?

**Comment by fer0n** [comment]
I couldn't find a way to disable it. It works quite well and I don't think anyone would hit it by accident

**Comment by EricBAndrews** [comment]
Took a quick look at Ivory:
- They have no accessibility HUD on the tab bar :(
- But their swipe left/right is a nifty little piece of UX we can absolutely filch

Also it looks like the top left is a tap, not a long press, though that might be different if you're not in demo mode. Either way that's a space we can't use since we're committed to the iOS navigation paradigm, under which that's a back button.

**Comment by fer0n** [comment]
I can tab on the profile picture or long press and drag to switch. They also show the navigation buttons there, but the profile picture if you didn't navigate anywhere. But since the main feed is already a layer down that's probably not ideal, I agree.
