### ISSUE TITLE
Animations on comment collapsing look slow

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#416]
(This below was for build 406)

This is partly a personal preference, but this is two parts of a bug via the following video:

https://github.com/mlemgroup/mlem/assets/22740616/0b98d24a-a886-4005-864c-4f8bdcddc2c9

1. The slowdown at the end of the animation curve makes the animation feel more slow than it actually is, and makes it feel drag on. I'd suggest making it linear or quicker (200ms max)
2. ~~The rest of the comments don't move equally with the speed of the collapsing/opening comment, they all feel disjointed (look at the bottom comments while I collapse the one at the top)~~

**Comment by boscojwho** [comment]
Yea, I got the same feeling while working on fixing a scrolling bug in this view. We're using the system built-in animations at the moment. What build are you using?

**Comment by boscojwho** [comment]
> This is partly a personal preference, but this is two parts of a bug via the following video:
> 
>  trim.6C41B03B-E7D3-4B29-8BF7-CAEFE06FB9FB.MOV 
> 1. The slowdown at the end of the animation curve makes the animation feel more slow than it actually is, and makes it feel drag on. I'd suggest making it linear or quicker (200ms max)
> 2. The rest of the comments don't move equally with the speed of the collapsing/opening comment, they all feel disjointed (look at the bottom comments while I collapse the one at the top)

Yea, I got the same feeling while working on fixing a scrolling bug in this view. We're using the system built-in animations at the moment. What build are you using?

**Comment by ShadowJonathan** [comment]
406, I just saw this wasn't the latest, so lemme update

**Comment by ShadowJonathan** [comment]
Looks better, though I think the animations could still be quicker, is that alright?

**Comment by boscojwho** [comment]
Yea, probably changing it to `.linear` instead of `.easeOut` would make it feel snappier.

**Comment by boscojwho** [comment]
So it's currently a spring animation:
- Changing it from `.interactiveSpring(response: 0.4, dampingFraction: 1, blendDuration: 0.4)` to `.interactiveSpring(duration: 0.25)` made it feel much snappier, but that's personal taste.

Might rig up a "Developer Menu" where we and test users can play around with these values in dev and TestFlight builds.

**Comment by ShadowJonathan** [comment]
Wouldn't recommend no animation, as that could be very jarring and confusing what happened

**Comment by boscojwho** [comment]
@ShadowJonathan You might like this even more (yes, the expand animation is a bit janky)
https://github.com/mlemgroup/mlem/assets/2549615/6194af02-e6bd-4d75-856a-9857eb5bc004

**Comment by ShadowJonathan** [comment]
Yeah, it's pretty fast enough, thanks :)

Is there a way to fix that janky animation?

**Comment by boscojwho** [comment]
> Yeah, it's pretty fast enough, thanks :)
> 
> Is there a way to fix that janky animation?

Possibly, poked around this for a bit: 
- Moving the transition to the comment itself improves the animation (presumably gives SwiftUI more context), but the child comments interfere with user interaction while animating for some reason.
- It might also have to do with the nested VStacks (I say this partly because I wrote up a test project that presents parent/child comments using a `List` -> `Section` -> `OutlineGroup` with custom disclosure style, and it animates nicely until I wrap the custom disclosure in a VStack).
Nice (without VStack)
https://github.com/mlemgroup/mlem/assets/2549615/e8712bf1-255a-4f68-aa53-7b726d28cfe3
Not so nice (with VStack)
https://github.com/mlemgroup/mlem/assets/2549615/3ea54128-d9d0-42d3-ad35-0f6176e552db
