### ISSUE TITLE
Automatic Refresh and Scroll-to-top Feature on "Feeds"

### ISSUE THREAD

**Issue by AlphaPro06** [mlemgroup/mlem#42]
## Introduction
This proposal aims to improve the user experience in the "Feeds" section of Mlem, an iOS client for Lemmy.

## Requirements
We propose two enhancements:

    Auto Scroll-to-Top: On tapping "Feeds," the view should auto-scroll to the top.
    Auto Refresh: The feeds should auto-refresh when "Feeds" is tapped, displaying the latest posts.

## Discussion

**Auto Scroll-to-Top**

Auto-scroll will remove the need for manual scrolling when users want to revisit the top of the "Feeds."

**Auto Refresh**

Auto-refresh, combined with auto-scroll, will ensure users always see the most recent content with a single tap, enhancing usability and efficiency.

## What I Need
1. Code Adjustments: Modify the "Feeds" button's click event to enable auto-scroll and refresh.
2. Testing: Ensure the feature works as expected and doesn't impact app performance.
3. User Feedback: Gather and analyze user feedback post-deployment.
4. Iterative Improvements: Refine the feature based on feedback and observed user behavior.

**Comment by irodrigo17** [comment]
Hey! I'd like to help with this, seems like a good ramp up task.

I'll wait for it to be assigned to me before I start coding.

**Comment by irodrigo17** [comment]
> Imo refreshing should be an explicit pull-down action, not a toast. Maybe a "pull down to refresh" non-interrupting popup when people try to tap multiple times while at the top.
> 
> Maybe the function of tapping the tab button while at the top would be to scroll back down to the previous scroll position.

Actually, I really like these ideas! Happy to help build this instead of the original proposal if there's consensus.

Seems this task needs a bit more discussion though, should it be moved to the "In Discussion" column?

**Comment by Sjmarf** [comment]
> Maybe the function of tapping the tab button while at the top would be to scroll back down to the previous scroll position.

This is a good idea - in Apollo, tapping the header scrolled to the top, and tapping it again scrolled back the original position. The scroll-to-top functionality of the header is built into NavigationStack, but scrolling back to the original position when you tap again is not.

**Comment by boscojwho** [comment]
Tap on tab to navigate is addressed in PR #545

**Comment by EricBAndrews** [comment]
Marking as closed as of #545. Refresh on scroll to top will not be implemented in favor of navigation back to community view.
