### ISSUE TITLE
Gesture to close quick look image preview

### ISSUE THREAD

**Issue by tombuben** [mlemgroup/mlem#421]
It is currently very easy to open the quick look by tapping g any image on screen, but to close it you have to reach to the very top right of the screen and press "Done".

If there was a swipe away gesture to close the view it'd be much more pleasant to use.

**Comment by ShadowJonathan** [comment]
This is the same as how it was done in Apollo, and an essential feature to the preview imo

**Comment by boscojwho** [comment]
@EricBAndrews mentioned something about a new fancier image viewer in the works, but I'm not sure when that'll be ready.

If that's not going to be ready in the next few weeks, we could easily spin up a SwiftUI.UIViewRepresentable version of QuickLook in a day and make users happy in the mean time? =)

**Comment by EricBAndrews** [comment]
Absolutely, I'd happily merge that PR--this is probably our #1 request right now. Do you want the issue? You seem to have an implementation in mind

**Comment by boscojwho** [comment]
> Absolutely, I'd happily merge that PR--this is probably our #1 request right now. Do you want the issue? You seem to have an implementation in mind

Yea, might be able to get to this today or tomorrow =)

**Comment by boscojwho** [comment]
This has been addressed =) See #460
