### ISSUE TITLE
Experimental Settings menu for developers and beta users

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#427]
## Introduction
An experimental settings page that allows:
- Developers to quickly test certain values (e.g. animations or layout) on actual devices without having to manually recompile
- Beta users to provide useful feedback by varying certain values to their liking.

## Requirements
- [ ] Ability to determine what deployment environment app is running in.
- [ ] Add "Experimental" section to settings view.
- [ ] Ensure experimental settings values are never used in production builds.

## Discussion
We need a way for our code to seamlessly use production values on App Store builds, and use experimental values on other builds.
- Currently, settings values are stored in UserDefaults with the `@AppStorage` property wrapper.
- Perhaps a property wrapper like `@Experimental` could work?

**Comment by Sjmarf** [comment]
We have a page for developer toggles under Advanced -> Developer.
