### ISSUE TITLE
Rename "vote complex" inside settings to something more understandable for users

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#429]
Since we're developers, ofc we know what it is, but users might be very confused as to what it's referencing.

Also the button is significantly bigger than the other ones, and it looks off cuz of it

**Comment by JakeShirley** [comment]
Sounds like this naming is giving users... a complex.  😎

**Comment by EricBAndrews** [comment]
Button size should be handled by #248 

As for what to call it, how's "vote button style?"

See also #411 re: naming

**Comment by ShadowJonathan** [comment]
"Vote button style" should work

**Comment by EricBAndrews** [comment]
Irrelevant due to widget wizard
