### ISSUE TITLE
Tab/navigation bar appearance: non-translucent

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#435]
I'd love to have an option to make the tab bar and navigation bar non-translucent. Just personal preference, but it would fit in with the other appearance options there are.

I'd be happy to take a look at this and see if I can manage to implement it myself.

**Comment by EricBAndrews** [comment]
Slating for 1.2 customization alongside animation toggle and profile label customizability.

**Comment by fer0n** [comment]
Would you mind if I take a look at this?

**Comment by fer0n** [comment]
@EricBAndrews Would you mind if I took a look at maybe implementing this?

**Comment by fer0n** [comment]
@EricBAndrews I took the freedom to create a PR for this (#483). I'd be happy if you could have a look, but I totally understand if that's not a priority and you got other things to do.
