### ISSUE TITLE
Emphasise post headlines more for large post sizes

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#437]
## Introduction
I find it sometimes hard to focus on content in the the large post size feed, because everything looks very similar.

## Requirements
Emphasise the post headlines more.

## Discussion
It would help a lot to put more emphasis on the post headlines (especially for text posts) by de-emphasising the body of the posts, like so (upvote buttons are also de-emphasises slightly): 
![Comparison/proposal](https://github.com/mlemgroup/mlem/assets/20093825/a5b5fb04-a99e-4139-8b11-e0c7f0478724)

**Comment by EricBAndrews** [comment]
I like the idea of graying out the post text a lot. Putting this under 1.2 because 1.1's already got scope creep problems but I'd happily merge this PR whenever.

**Comment by fer0n** [comment]
That was just a mockup, but I might have a look at implementing it

**Comment by fer0n** [comment]
@EricBAndrews not sure if I understood you correctly there and you'd prefer to not deal with this at all for now and I'll remove the PR again. If not and you wanna have a look, I made a very simple implementation of this here: #451

**Comment by fer0n** [comment]
I guess this can be closed sind's it's merged already?
