### ISSUE TITLE
Remove animation from tab bar

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#439]
## Introduction
The tab bar animates the "selection" color in and out when selecting a different tab. This makes the transition feel unnecessarily slow.

## Requirements
Remove the transition from the tab bar items

## Showcase
Mlem transition:
![Slow Mlem transition](https://github.com/mlemgroup/mlem/assets/20093825/bb330605-884b-4449-9578-654d97f2aa7b)

For comparison, inside the App Store App:

![Comparison App Store App](https://github.com/mlemgroup/mlem/assets/20093825/0ca3d90e-3ec9-4079-8477-8b11ef4ddac8)

**Comment by EricBAndrews** [comment]
This should be something the user can toggle. Slating for 1.2 customizability update.

**Comment by fer0n** [comment]
You mean as a customization option? I'm not sure if that'd be taking customization a bit too far.

I'd argue the transition doesn't add much and mostly slows things down (and afaik it isn't a standard behavior that you'll find anywhere else on iOS). But it's of course up to you, whether you want to add a setting, keep the transition, or ditch it :)

**Comment by EricBAndrews** [comment]
I've heard positive feedback on the animation from other users, so I think it's something that lands squarely in the "should be toggle-able" category. 

We can also definitely look into making the animation a little snappier.

**Comment by Sjmarf** [comment]
I slightly prefer it without the animation, but I don't really care either way - will people really take the time to customise this? It seems like a really tiny thing to make customisable

**Comment by fer0n** [comment]
@Sjmarf I agree. I also prefer the removed animation, but I'd rather have the current one than an option to customize it. Seems to be taking things a step to far.
