### ISSUE TITLE
Add .webp to the list of image file extensions

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#44]
Example: https://lemm.ee/post/505905

https://github.com/mormaer/Mlem/blob/69e55989bf033185857cee8bda546ff2503ca87a/Mlem/Extensions/URL%2BIdentifiable.swift#L14

**Comment by jeltebr** [comment]
I would like to take this issue

**Comment by JakeShirley** [comment]
@jeltebr I assigned it to you, can't wait to see the PR!
