### ISSUE TITLE
Scrolling micro-stutters

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#446]
**Describe the bug**
Scroll the feed

**Expected Behavior**
Smooth scrolling

**Actual Behavior**
Small hiccups/stutters when scrolling

**To Reproduce**
Scroll the feed and let it come to a stop by itself. If I'm seeing this correctly there's one small freeze when slowly coming to a stop. Might be just coincidence though at it simply comes from pre-loading posts.

[showcase video](https://github.com/mlemgroup/mlem/assets/20093825/46834792-7b73-4097-b45f-29cce47cf061)

**Mlem Information:**
1.0.1 (432)
iPhone 12 Pro

**Comment by fer0n** [comment]
Scrolling up is also skipping around occasionally. Not sure if that's a similar issue: [video](https://imgur.com/a/Rzw8nnA)

**Comment by EricBAndrews** [comment]
Re: scrolling up: 

If you scroll down fast enough that the images higher in the feed don't have time to load, the scrolling back up will skip a bit as the image resizes. That's an unsolvable issue as far as I can tell--preventing the skipping requires informing SwiftUI of the frame size, which you can't do until the image loads.

Fortunately users don't just spam scroll down and then peruse back up all that often, so it's not a huge issue.
