### ISSUE TITLE
Tapping the avatar of the community from a post will show it in quick view, while tapping it on a profile does nothing

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#455]
I wanted to navigate to the community by tapping anywhere on the "community" section of a post, but instead I got a quick view of the community avatar.

When I viewed the community sidebar, I couldn't view the avatar in quick view by tapping on it.

**Comment by EricBAndrews** [comment]
Closed, can't remember the PR--I fixed this as a "by the way" in another one
