### ISSUE TITLE
Upvote, downvote & save buttons animation glitch

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#465]
Repro:

- Upvote a post
- Remove upvote
- Press save
- Unsave
- Press upvote again
- Green save button flashes

This can be reproduced for downvote & save too.

https://github.com/mlemgroup/mlem/assets/78750526/b2cdd817-f02c-4c58-b882-9e5a140b0538

**Comment by EricBAndrews** [comment]
I think this issue will be resolved by #73 when state faking is done properly at the model level--see #396 for an example implementation

**Comment by EricBAndrews** [comment]
Closing as dupe of #73
