### ISSUE TITLE
Remove Avatar stroke for certain instances.

### ISSUE THREAD

**Issue by WestonHanners** [mlemgroup/mlem#47]
## Introduction
Not gonna beat around the bush, this is a Beehaw specific fix but we can extend it to others on an opt-in basis.

The circle stroke looks weird on Beehaw instance avatars that are hex shaped, lets remove the stroke for this specific instance since it is so big.

## Requirements
Create an array somewhere with a list of instances to opt-out of avatar stroke.. add beehaw.org to the list.
Remove stroke if instance is in this list.

Update community avatar in posts, and in sidebar, but not user avatars.

**Comment by EricBAndrews** [comment]
Resolved, can't find PR because repo migration

**Comment by BrooklynMan** [comment]
is this necessary for *any* instance? can we just remove it altogether?

**Comment by EricBAndrews** [comment]
Closed a long time ago, can't find PR num but it does this
