### ISSUE TITLE
Swipe to collapse comment

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#473]
## Introduction
Ability to use swipe action on a comment to collapse it.

## Requirements
- [ ] Add collapse action to swipey actions.

## Discussion
This was a feature in Apollo, and I personally used it because there were too many tap targets in comments.
- I had this set to be the last swipe action from the right in Apollo, but eventually this should be customizable in settings.

**Comment by EricBAndrews** [comment]
Closed in #557
