### ISSUE TITLE
Cursor jumps to the end when starting to edit a post/comment

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#474]
**Expected Behavior**
If I move the cursor somewhere and start typing, it should enter the text at the cursor.

**Actual Behavior**
The cursor jumps to the end after the first typed letter.

**To Reproduce**
- tap edit in the contextMenu of a comment or post
- move the cursor somewhere else
- start typing 
- the first letter will be where the cursor was, but everything else will be at the end 
![video](https://github.com/mlemgroup/mlem/assets/20093825/81b1661a-5e9e-42b6-9a38-54dc2c2d1f96)

**Mlem Information:**
1.0.1 (475)
iPhone 12 Pro, iOS 16.6

**Comment by EricBAndrews** [comment]
That's very strange--probably due to #433 if I had to guess.

Unable to replicate on my own device:


https://github.com/mlemgroup/mlem/assets/44140166/69ae1310-5c23-497f-8d39-70ab47643326

**Comment by fer0n** [comment]
@EricBAndrews this has been around before the latest release. Maybe the view re-renders after the first change? I also added my device information

**Comment by fer0n** [comment]
I reinstalled the app and at least so far, it's not come up again. I'll update if it does

**Comment by fer0n** [comment]
It's back again. I tried a few different settings, restarting it etc., but it's always there now. Always after the first character and always working after.
