### ISSUE TITLE
Save as image in quick view

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#479]
Currently, when opening quick view, I can save the image via the top part of the view, but not via the bottom share sheet;

![image](https://github.com/mlemgroup/mlem/assets/22740616/e610de9e-e965-4b39-90e0-9e61dfd15edd)

![image](https://github.com/mlemgroup/mlem/assets/22740616/5e6b8195-b90a-48c2-b5fb-1c07f82bd543)

![image](https://github.com/mlemgroup/mlem/assets/22740616/fae3dc44-2d6a-43e1-88f6-e74e4e0c2f9b)

(Additionally, when things are indeed saved, I'd like for them to be saved to a separate album, "Mlem", like Apollo did)

**Comment by EricBAndrews** [comment]
Closing as "not planned"--quick look is a band-aid, @tht7's image viewer should have this functionality
