### ISSUE TITLE
Clarifying which instance you are logged into

### ISSUE THREAD

**Issue by Guy-Dudeman** [mlemgroup/mlem#49]
There have been a number of comments about users not knowing what instance they are currently logged into.

I propose adding the instance name to the very top of the title bar, above the feed indicator:

![LemmyHeader](https://github.com/mormaer/Mlem/assets/136025639/32d4751f-dd71-432e-a69e-708d91f3b2f1)

**Comment by EricBAndrews** [comment]
Closed in #467
