### ISSUE TITLE
Local feed is empty on lemdro.id

### ISSUE THREAD

**Issue by Rexios80** [mlemgroup/mlem#490]
**Describe the bug**
Log in with a lemdro.id account and open the local feed

**Expected Behavior**
The feed is not empty

**Actual Behavior**
The feed is empty

**Mlem Information:**
1.0.1 (475)

**Additional Context**
Local feed works with other instances

**Comment by JakeShirley** [comment]
It seems to be working for me locally.

![image](https://github.com/mlemgroup/mlem/assets/1000311/cb1753fc-6c15-45f4-9355-e2d25f0ff825)

**Comment by Rexios80** [comment]
![image](https://github.com/mlemgroup/mlem/assets/7896519/ef372d66-0375-46b8-a4f3-9ac2b1f296cf)

**Comment by JakeShirley** [comment]
OK I reproduced locally.  I think this is more of a Lemmy/lemdro.id issue. You are sorting by "active" and the instance is reporting nothing back.  "Active" is a bit busted in Lemmy right now I think.

**Comment by Rexios80** [comment]
I tried changing sort options and it didn't fix it

**Comment by JakeShirley** [comment]
Ok I spoke too soon, this actually seems like we are eating an error here.

I got the following in the console:
```
Setting sort type for 'feed local' to 'Active'
☠️ ERROR ☠️
🕵️ -> dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "posts", intValue: nil), _JSONKey(stringValue: "Index 30", intValue: 30), CodingKeys(stringValue: "post", intValue: nil), CodingKeys(stringValue: "url", intValue: nil)], debugDescription: "Invalid URL string.", underlyingError: nil))
📝 -> The data couldn’t be read because it isn’t in the correct format.
📂 -> Mlem/ContentView.swift | body | line: 81
```

**Comment by Rexios80** [comment]
Actually "old", "most comments", "top" of 6/12/week/month/year/all work but none of the others

**Comment by JakeShirley** [comment]
Based on the error above it seems to be specific posts causing the failed parsing.  Trying to chase it down now.
