### ISSUE TITLE
Consistent background

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#493]
Right now the background area of the app is inconsistent, using .secondarySystemBackground in Feeds, Search, and Settings, and using .systemBackground in Inbox, Profile, and Community List.

This should be made consistent, although I'm not sure which way it should go--hence "In Discussion."

This will also remove the need to have different background options depending on the opaqueness of the insets.

**Comment by fer0n** [comment]
I think `.systemBackground` makes more sense and seems to also be the default in Apple's apps. Additionally, it leads to less pop-in when starting the app in dark mode and seeing the "loading" message.

**Comment by EricBAndrews** [comment]
Closed with 2.0 design changes
