### ISSUE TITLE
Small Memory Leaks

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#499]
**Describe the bug**
I ran the profiler while scrolling through the feed and switched to the different tabs, some memory leaks popped up

**Expected Behavior**
No memory leaks

**Actual Behavior**
Small memory leaks

**To Reproduce**
- Run the app in Xcode, ideally on a physical device
- Go to Debug navigator - click on memory - Profile in instruments
- Use the app and watch the "Leaks" track in the profiler

<img width="1284" alt="Screenshot 2023-08-13 at 21 47 51" src="https://github.com/mlemgroup/mlem/assets/20093825/e3742247-6158-49f7-8a57-f3e0d4c00310">

**Mlem Information:**
Current dev commit (284693d798436635c176631a592ab33949279)

**Additional Context**
I don't think it's a huge issue currently, but I thought I'd mention it anyways. I know that it can be quite difficult to find out where that's coming from (although I'm not an expert in that and I'm sure others are much better at this). I know that sometimes using bindings in a certain way or some other state related things can lead to leaks. Sometimes it's probably just SwiftUI.

**Comment by EricBAndrews** [comment]
Closing as stale since this is a bug against the v1 codebase
