### ISSUE TITLE
New Settings Icons

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#50]
I'm personally not a fan of the small settings icons we have currently. What do people think about making them larger?

What we have currently: 

![IMG_9098](https://github.com/mormaer/Mlem/assets/78750526/195dd25a-872d-423e-b146-ad5b8c42f7f5)

Quick mock-up of what larger icons could look like:

![image](https://github.com/mormaer/Mlem/assets/78750526/3cb7dc8a-6d57-45be-868d-ea1ce6f85224)

What do people think? I'm open to suggestions if anyone wants me to make other mock-ups.

In the second image, the top four icons are from SF symbols, and the 'About Mlem' icon is a simplified version of the Mlem app icon.

**Comment by EricBAndrews** [comment]
Closed in #312
