### ISSUE TITLE
Add universal confirmation dialog for destructive changes

### ISSUE THREAD

**Issue by einsteinx2** [mlemgroup/mlem#508]
## Introduction
Right now for menu options like "Block User", it's possible to accidentally tap it, then the post is immediately removed and there's no easy way to undo the action. 

That's just one example, but there are/will be many examples of "destructive" changes. I think creating a reusable UI component to confirm actions that can also store whether to prompt again for that action would be helpful and can then be reused all over the app.

## Requirements
See discussion section

## Discussion
My thinking is it would work like this:

1. Create an enum of different destructive actions
2. Create a reusable bit of code that displays a prompt with 3 options: confirm, cancel, and "don't ask again"/"auto-confirm" (not sure on naming of last one but you get the idea)
3. If user selects the "don't ask again" option, that can be persisted using the enum value
4. A settings section would be added that would allow users to remove these if they want to be prompted again in the future
5. Then anywhere in the app that a destructive action of some kind will be performed, a new enum value can be added if needed and this dialog can be trivially used.

This would provide a consistent experience across the app, and would make it trivial for devs to add confirmation support to new features.

## What I Need
A consistent way to confirm destructive changes.

**Comment by EricBAndrews** [comment]
Child of #371

**Comment by EricBAndrews** [comment]
Closed in #579
