### ISSUE TITLE
New 'About Mlem' menu

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#51]
The 'About Mlem' section under Settings could be improved to include:

-  A link to the matrix room.
- A link to the Github. Or perhaps separate 'Report bug' and 'Suggest feature' buttons, which link to the respective Github issue templates.
- The c/mlemapp link could be moved to inside About Mlem, and could open the community in-app rather than in a WebKit view.

**Comment by yoav-lavi** [comment]
I was going to post here about adding a GitHub link, agreed

**Comment by WestonHanners** [comment]
We also need to update the libraries list and contributors

**Comment by Sjmarf** [comment]
Mock-up of what this could look like

![simulator_screenshot_D892F2B6-CC17-41BB-85B7-1D56489C8FDC](https://github.com/mlemgroup/mlem/assets/78750526/5e3d839a-2b63-4322-8c62-24212a82b702)

**Comment by WestonHanners** [comment]
PR is up for new UI is in 1.0, we can improve it in a future release.
