### ISSUE TITLE
Show cropped images with blurry borders

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#515]
When I scroll through posts, the images that don't entirely show their full size inside of the square are hard to differentiate from images that do show their entirety within the borders.

To counter this, could I suggest to "blur" the edges of the border(s) that hide more of the image? This way, I know that I need to tap to see more, and can differentiate instantly.

**Comment by EricBAndrews** [comment]
Should be resolved by #501 and #503--images that are too tall are shrunk to fit the max height, and max height can be toggled to arbitrarily large.

**Comment by ShadowJonathan** [comment]
Are images that are too large for their preview shown as such? Can I differentiate between the ones that got previewed completely, or cropped?

(This is why I want the blurry border)

**Comment by EricBAndrews** [comment]
Images that are too large are shrunk--nothing gets cropped
