### ISSUE TITLE
Ability to look at local timelines

### ISSUE THREAD

**Issue by Adi1200** [mlemgroup/mlem#516]
## Introduction
I was using the ‘Ice Cubes’ Mastodon client, I thought the local timeline feature was neat. 

## Discussion
It allows you to view and comment on the timelines of other instances as if they were your own.

![IMG_1199](https://github.com/mlemgroup/mlem/assets/94178473/9112a8cd-0602-49e3-be20-15d8d80f776f)

**Comment by EricBAndrews** [comment]
Closing this as duplicate since this functionality will be largely implemented once we have #21 in
