### ISSUE TITLE
Open Lemmy links in app, rather than in the embedded web browser

### ISSUE THREAD

**Issue by Adi1200** [mlemgroup/mlem#517]
## Introduction
It’s pretty annoying when you press a link and it opens the embedded browser

## Discussion
Rather, it should simply open it in the app

https://github.com/mlemgroup/mlem/assets/94178473/0a0e9323-be25-4ec0-a6e1-1fbed3fc15a1

**Comment by chrismcr** [comment]
I have a trivial fix for this that adds a new toggle in general settings, so unless there are other plans can it be assigned to me so I can put up a PR?
