### ISSUE TITLE
*  image in comments causes text to render off screen

### ISSUE THREAD

**Issue by cryocaustik** [mlemgroup/mlem#520]
**Describe the bug**
What did you do to trigger the bug?
Browsing large comment thread, came across a nested comment with an embedded image, that caused text to be rendered offscreen 

**Expected Behavior**
What did you expect to happen?
Image and text should be limited to the size of nested comment

**Actual Behavior**
What actually happened?
nested comment with an embedded image, that caused text to be rendered offscreen 
![image](https://github.com/mlemgroup/mlem/assets/15346996/9640e566-7ab8-42a9-8260-26a281a7ef2f)

**To Reproduce**
Open large comment thread with embedded image in a nested comment 
Example: https://lemmy.world/post/3353774

**Mlem Information:**
Mlem 1.0.1 (483) from TestFlight 

**Additional Context**
using iPhone 12 Pro Max running iOS 17 beta 6

**Comment by boscojwho** [comment]
Fixed in some earlier PR for `.image` post types.
Fixed in #630 for `.link` post type.
