### ISSUE TITLE
* Comment sorting shows wrong icon/sorting when viewing a post

### ISSUE THREAD

**Issue by catniptree** [mlemgroup/mlem#528]
https://github.com/mlemgroup/mlem/assets/138243705/499d127b-4dce-47c9-83c6-d81b366cae2d

**Describes the bug**
Comment sorting displayed on a post does not reflect the setting.
I set comments to **Hot**, but the sorting menu says comments are sorted by top.

**Expected Behavior**
Comment sorting should show/reflect the correct sorting setting.

**Actual Behavior**
Comment sorting is displayed wrong.

**To Reproduce**
Open a post and check it comment sorting reflects the setting from general settings.

**Mlem Information:**
1.0.1 (483)

**Additional Context**
See attached video.

**Comment by boscojwho** [comment]
Ah, makes sense, added a fix =)
