### ISSUE TITLE
Preload a few images below the viewport

### ISSUE THREAD

**Issue by CDeLeon94** [mlemgroup/mlem#532]
Images take a second to load, as a result they appear to *pop* into existence when they're already halfway up the screen. Preloading to some extent will alleviate this issue and make scrolling much more visually pleasant.

**Comment by EricBAndrews** [comment]
Image preloading begins the moment the post is loaded (i.e., up to 50 posts in advance)--if either your connection or the image host is slow, it might not get there in time.

There are possibly some final size adjustments that are causing a momentary hang in image delay that should be smoothed out in an upcoming middleware PR, but the only way I can consistently reproduce this issue on a fast Lemmy instance is by throttling my bandwidth so I'm going to tentatively mark this one down as a network issue.

We have a "slow internet" mode that reduces the number of concurrently loaded posts, which might help (settings -> general -> internet speed, not sure which (if any) public builds it's out on though).

Going to hold off on marking this as closed for a couple days in case you have further input.

**Comment by CDeLeon94** [comment]
Even with the slow internet mode, I'm seeing the popping in. But it feels too consistent to be a network issue. And seems to happen irrespective of how fast I scroll, which I would not expect if it was a network issue (I'd expect if I scrolled very slow I could stay above the preloaded images) 

So I think what I'm experiencing is this resizing issue you mentioned.

**Comment by EricBAndrews** [comment]
Still present?

**Comment by CDeLeon94** [comment]
1.1.2 (792) 

Yep

**Comment by EricBAndrews** [comment]
This should be well and properly fixed in 2.0
