### ISSUE TITLE
Conventions Convention

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#55]
How should we format our code?

Discuss.

**Comment by ShadowJonathan** [comment]
cc @mormaer and @JakeShirley since they have been working on this

**Comment by Sjmarf** [comment]
Filenames should have no spaces and should match the name of the struct/class inside of the file where possible imo.

**Comment by tht7** [comment]
I know that the current file names are weird like who tf puts spaces in file names
Buttt it’s kinda growing on me, feels oddly friendly

**Comment by mormaer** [comment]
Don't succumb to the dark side @tht7 - stay strong

I'd vote for any new files we create being in `UpperCamelCase` and matching the struct/class they contain as @Sjmarf said... it's the sane choice 🙃

It'd be worth fixing the others but given the potential nightmarish rebases against large changes to the project file I'd perhaps suggest if/when a particular file is refactored, we fix the file name at the time rather than an _all at once_ approach

**Comment by EricBAndrews** [comment]
Personally I prefer the spaces--there isn't any downside to it (it's not like we're navigating through this on a terminal--Xcode handles spaces very nicely), and it makes the file name easier to read. The only reason to use CamelCase is when it's actually impractical to use spaces. 

It's a very minor concern either way, though, so if people like the CamelCase I don't mind using it

**Comment by Sjmarf** [comment]
Either way, we should decide on a consistent naming scheme and stick with it - currently, some files use CamelCase whilst others use TitleCase. 

Every other Swift project I've worked on uses CamelCase for filenames, and so do all of the most popular Swift projects I've seen ([CodeEdit](https://github.com/CodeEditApp/CodeEdit), [Whisky](https://github.com/IsaacMarovitz/Whisky/tree/main/Whisky/Views), [Firefox](https://github.com/mozilla-mobile/firefox-ios/tree/main/Client/Frontend/Home), etc). I'm yet to see a project that _doesn't_ do this, and thought it was some kind of standard.

I'd prefer to use CamelCase for consistency, but don't really mind either way.

**Comment by boscojwho** [comment]
I was definitely thrown off by the spaces in some filenames. For example, when I was looking for `AppState` using `Open Quickly`:
- Typing `appstat` shows two seemingly unique results.
<img width="459" alt="Screenshot 2023-07-24 at 2 43 34 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/fa866a89-62d5-4627-b4ca-851cb1e4ffc2">

- Typing `app stat` only returns one result.
<img width="460" alt="Screenshot 2023-07-24 at 2 44 14 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/6970f545-628d-46e8-81b9-ccd1f4a889d9">

- Which means, we'd have to type `appstate` to get `AppState` the class itself.
<img width="455" alt="Screenshot 2023-07-24 at 2 45 08 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/d7d196ff-229e-413a-bb06-a2e27b37f5e6">


Obviously, this is only relevant if the file only contains one type with the same name, but it gets a little tedious having to possibly think about this when you're just trying to open something quickly.

PascalCase has definitely been the convention not just in Swift, but also Objective-C, Cocoa (Touch), and first/third party Apple ecosystem frameworks. Much of this is cultural (especially within the "indie" Apple dev community), but Apple also loves to be opinionated on this subject. For example: See here [for an old Apple article](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html) on naming header files in Objective-C. I couldn't find Apple's newer documentation that directly discusses filenames, but Apple's own repos also use Pascal Case, for example [apple/swift-syntax](https://github.com/apple/swift-syntax)

I guess it's not a big deal, as long as we don't do snake case 😆😆
