### ISSUE TITLE
Haptics for swipe and upvote are too strong

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#56]
This is something I'm noticing as I'm using the app; I'm way too distracted and "buzzed" by the vote and swipe "taps", they're way more stronger than apollo.

Whereas in Apollo the swipe and vote actions are more like soft feedback, in Mlem they're done by the "success" haptic, which is a double (imo stronger) tap, which feels too stimulating when done in quick succession, or when doing it a bunch of times at all.

**Comment by EricBAndrews** [comment]
Resolved in #316
