### ISSUE TITLE
(Typing this on mobile, apologies if anything is too brief / unclear, feel free to ask)

### ISSUE THREAD

**Issue by froztbyte** [mlemgroup/mlem#563]
## Introduction
mlem uses webviews for any links clicked, and offers no alternative. I want not-that

## Requirements
Provide a toggle to respect/use system-configured browser

**Comment by boscojwho** [comment]
You mean open links in Safari or Chrome, etc., instead of opening links in the system in-app browser?

**Comment by eirnym** [comment]
Please add at least an option to open links in a default browser. It's not required to list all installed browsers for that feature

**Comment by eirnym** [comment]
@froztbyte could you please edit your original message to reflect the statement?

**Comment by Sjmarf** [comment]
Added in #859
