### ISSUE TITLE
Common Clause.txt needs to be added

### ISSUE THREAD

**Issue by BrooklynMan** [mlemgroup/mlem#6]
GPL.txt and CommonClause.txt need to be added

files attached

[commom-clause-1.0.txt](https://github.com/mlemgroup/mlem/files/11931846/commom-clause-1.0.txt)
[gpl-3.0.txt](https://github.com/mlemgroup/mlem/files/11931847/gpl-3.0.txt)

**Comment by WestonHanners** [comment]
is there a typo in commom-clause file?

**Comment by BrooklynMan** [comment]
these files have been transferred. it seems I was being overly-cautious.
