### ISSUE TITLE
Actions when tapping the current tab (go back to top level, scroll up)

### ISSUE THREAD

**Issue by isametry** [mlemgroup/mlem#60]
## Introduction
First of all, čau Davide :) and hi everyone else! Love the project so far and can't wait to see it evolve further!

Now, to the point: By convention, tapping the current tab at the bottom of the screen (e.g. tapping “Settings” when the user is already in Settings) does some action – either to go back, or to scroll up – depending on the current view. 

## Discussion
So the typical behavior (at least from my observations) is:

0. (Scroll up in current view first. This is not always the case, but examples exist – e.g. browsing an album in Photos),
1. Go back to the topmost level of that tab,
2. If the user is already at the topmost level, scroll up if applicable.

See other tabbed built-in apps for examples: Files, Health, App Store, etc.

## Requirements
1. Determine what is the “base view” in each tab. I guess `Messages`, `Profile` and `Settings` are obvious, but not sure about `Feeds`. Is the actual feed itself the top level item, or is it the list of accounts? iOS provides examples of both behaviors (compare the `Contacts` tab in Phone, vs. the `Shortcuts` tab in Shortcuts).
2. Implement tab back actions as described above.

## Remarks

This is related to mlemgroup/mlem#42, which already mentions the 2nd part – the scrolling behavior.

Maybe this would be fixed by mlemgroup/mormaer-mlem#29 automatically, I'm not familiar enough with iOS development to tell.

Thanks in advance for any input!

**Comment by ramzzzay** [comment]
I'm here to say: I always tap on tabs by muscle memory and always silently say in my brain "Ah, this is Mlem, here we are don't have this feature yet"

So, yes, this feature is VERY useful! It will be pleasant, to see in future updates!
