### ISSUE TITLE
New post composer destroys composed post without confirmation on down-swipe

### ISSUE THREAD

**Issue by mbs** [mlemgroup/mlem#602]
**Describe the bug**
The "New Post" composer destroys the post without confirmation on down-swipe.

**Expected Behavior**
Either nothing, or at least confirm that the draft post should be lost.

**Actual Behavior**
Post was lost.

**To Reproduce**
Feeds -> click a subscribed community -> Three dots [...] -> New Post -> painstakingly compose a longpost (actually any inputs will do) -> barely swipe down anywhere in the post popup/tab (e.g. while attempting to reposition the carat in the body, or on the titlebar, etc)

**Mlem Information:**
1.0.1 (483)

**Additional Context**
n/a

**Comment by boscojwho** [comment]
Improved in #633
- Can no longer swipe to dismiss if there's content in post composer.
