### ISSUE TITLE
* feeds don’t load with latest lemmy version (world et al)

### ISSUE THREAD

**Issue by th3dogcow** [mlemgroup/mlem#607]
**Describe the bug**
Lemmy servers upgraded

**Expected Behavior**
Fred’s (local, all, subscribed) to load

**Actual Behavior**
“no posts found”

**To Reproduce**
What steps do I need to take to trigger the bug?

**Mlem Information:**
1.0.2 (605)

**Comment by EricBAndrews** [comment]
Fixed in PRs mentioned above
