### ISSUE TITLE
Mask swipey actions bad behavior in comments

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#621]
Swipe actions sometimes try to also trigger context menu. On posts this renders as lag, in comments you see the duplication from the two animations--comments should also just "lag"

**Comment by Sjmarf** [comment]
I made a small tweak in #646 to fix a similar issue that might fix this one too

**Comment by EricBAndrews** [comment]
It looks like Apple actually fixed the bad behavior 🎉
