### ISSUE TITLE
Mark Read on Scroll

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#645]
When the "mark read on scroll" setting is enabled, posts would be marked as read automatically when they appear on your screen. Apollo had this

**Comment by rabidpug** [comment]
FYI looks like a PR was merged in October that enables batch calls for marking posts as read: LemmyNet/lemmy#4048

**Comment by Sjmarf** [comment]
Yep, I just saw that! I'll have a go at this one, just waiting for an in-flight tracker rework to get merged in first 👍

**Comment by EricBAndrews** [comment]
I've [prototyped a technique](
https://github.com/mlemgroup/mlem/tree/eric/mark-read-on-scroll) for detecting when to mark posts as read that feels pretty good.

That's the last technical blocker to this issue, so I'm slating it for 1.3.
