### ISSUE TITLE
Big gap on short images

### ISSUE THREAD

**Issue by Hikiru** [mlemgroup/mlem#650]
![IMG_6566](https://github.com/mlemgroup/mlem/assets/18605854/f964a8a4-d6fc-472e-b498-fd39fbc2672d)
![IMG_6567](https://github.com/mlemgroup/mlem/assets/18605854/307bafff-7ab2-496d-a842-1ea89ae0e45c)
Images are self explanatory

**Comment by EricBAndrews** [comment]
Square images are a temporary hack--scoped to return to normal when the media viewer comes out.
