### ISSUE TITLE
New Comments Indicator

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#654]
Add an optional indicator to the post view to tell the user if the post has new comments since they last viewed it. 

Backend:
It looks like the API has something approaching support for this--`read_post` performs a count of the comments at the time of read. If we can get that information when we fetch a post, we could use in the obvious manner to determine if there are new comments.

Frontend:
Replace the standard comment indicator with `text.bubble` when there are new replies

Ideally we could then highlight the comments themselves. It may be necessary to perform client-side caching of read comments, which shouldn't be *too* expensive--all we'd need to store is the `id`, which is only a few bytes.

**Comment by Sjmarf** [comment]
`PostView` has an `unread_comments` integer value that we could use to do this. It won't tell us *which* comments are new, but it'll tell us that they exist. https://join-lemmy.org/api/interfaces/PostView.html#unread_comments

**Comment by Sjmarf** [comment]
Added in #858
