### ISSUE TITLE
Improve gestures

### ISSUE THREAD

**Issue by JoseAmador95** [mlemgroup/mlem#66]
## Introduction

Apollo has a large set of customisation options for gestures (e.g., left/right swipe a post to like with two depth levels) which would be amazing to have in Mlem.

Particularly, swiping from right to left to return to the previous post/feed in case of an accidental left-to-right swipe.

## Requirements

* Add two depth levels when swiping posts and and comments.
    * Short swipe
    * Long swipe
* Add actions to each of the swipes.
    * upvote
    * downvote
    * reply/comment
    * share
    * save
* Disable left/right swipes in the app configuration.
* increase the swipe threshold to the middle of the screen.
    * example: Apollo does detect swipes if the gesture starts from the middle of the screen.

## Discussion

* Gestures are essential to the UX of an app, and the flexibility Apollo provides is superb.
* A personal use case is that I don't like to be forced to move my thumb to the left border to perform a left swipe gesture. Anywhere on the left side of the screen should be enough.

## What I Need

* Described above
* To copy Apollo, basically

#### Gesture settings menu

![image](https://github.com/mormaer/Mlem/assets/20510893/50e761c5-ab82-4fae-a5da-828d61656653)

#### Gestures for Posts

![image](https://github.com/mormaer/Mlem/assets/20510893/90b630bb-1510-4dcf-ba94-9d264148e365)

#### Gestures for comments

![image](https://github.com/mormaer/Mlem/assets/20510893/432120cc-aa3a-41ae-aad4-c1c077be4bd3)

#### Gestures for Profile posts and profile comments

![image](https://github.com/mormaer/Mlem/assets/20510893/0b88f353-030b-4d98-9774-a282a2892ea3)

#### Enable/disable gestures

![image](https://github.com/mormaer/Mlem/assets/20510893/9745a68e-27ea-44aa-915d-7a9bcf3be39e)

#### Gestures for going back to the previous feed and post

https://github.com/mormaer/Mlem/assets/20510893/28000e0d-1efe-456a-a352-ff7208869647

**Comment by BarterClub** [comment]
One I like from Reddit is the ability to change feeds by swiping. Home, popular, new, and so on.

**Comment by Sjmarf** [comment]
Closing as too broad scope. Relevant issues:

- #174
- #130
- #1409
