### ISSUE TITLE
[0.19.0] Instance blocking

### ISSUE THREAD

**Issue by mormaer** [mlemgroup/mlem#672]
## Introduction
As discussed in the recent Lemmy announcement users will now have the ability to block instances.

> Users can now block instances, so that their communities are hidden from listings. This is done via POST /api/v3/site/block with parameters int instance_id, bool block.

> https://github.com/LemmyNet/lemmy/pull/3869

## Requirements
We should add support for this as soon as possible, the option would need to be gated behind a version check as it will not be available below `0.19.0`.

**Comment by Sjmarf** [comment]
Another way to arbitrarily block an instance may be to use the load settings from json endpoint, which allows you to specify instance domains.
