### ISSUE TITLE
[0.19.0] - Cursor based pagination

### ISSUE THREAD

**Issue by mormaer** [mlemgroup/mlem#674]
## Introduction
As detailed in the recent Lemmy announcement the next version of Lemmy will allow for cursor based pagination.

> 0.19 adds support for cursor based pagination on the /api/v3/post/list endpoint. This is more efficient for the database. Instead of a query parameter ?page=3, listing responses now include a field "next_page": "Pa46c" which needs to be passed as ?page_cursor=Pa46c. The existing pagination method is still supported for backwards compatibility, but will be removed in the next version.

> https://github.com/LemmyNet/lemmy/pull/3872

## Requirements
We need to add support for this new style of pagination while remaining compatible with the original integer based page approach. After we see the majority of instances move to the newer version we can then remove the older approach entirely.

**Comment by Sjmarf** [comment]
The 0.18 pagination system will likely be discontinued in 0.20. By 0.20, we'll either have to drop support for <0.19 or find a way to support both.

>  0.19 supports both page and page_cursor. We will probably get rid of page in 0.20.

https://sh.itjust.works/comment/4349454
