### ISSUE TITLE
Some images fail to load in thumbnails

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#681]
Some community and user icons fail to load through `AvatarView` but load successfully in the larger icon shown at the top of the community/user page. c/apple_enthusiast is an example of this

**Comment by Sjmarf** [comment]
It should be noted that the avatars will probably fail to load in the profile/sidebar too after #689.

**Comment by boscojwho** [comment]
Is this always reproducible in `c/apple_enthusiast`? Testing on simulator and don't see this on latest dev build (with #689 merged in).

**Comment by Sjmarf** [comment]
Huh, I can't reproduce it now. A while ago, apple_enthusiast and a few others consistently didn't have a thumbnail image. I'll close this issue then (will reopen if it reappears)
