### ISSUE TITLE
Allow for setting smaller font sizes

### ISSUE THREAD

**Issue by raazman** [mlemgroup/mlem#71]
Having the option to set font size, specifically smaller fonts. Currently the fonts are pretty big in my opinion and would like to be able to set font sizes like on Apollo or the official Reddit app.

**Comment by EricBAndrews** [comment]
2.0 respects system font size, we do not plan to offer in-app font scaling.

**Comment by Sjmarf** [comment]
It's possible to change the font size for just Mlem in the system Accessibility Settings -> Per App -> Mlem -> Larger Text
