### ISSUE TITLE
Make tapping on an icon (such as feed or inbox) go back to that section

### ISSUE THREAD

**Issue by Hikiru** [mlemgroup/mlem#710]
I didn’t know how to describe it in a good way in the title. Basically, if you’re viewing a post or something else in the feed area, tapping the feed icon should go back to the feed. Another tap should take you to communities. Or if you tap on a comment from your inbox, tapping inbox should bring you back to the inbox. Most apps have this behavior so it feels awkward when I’m using Mlem when I have to swipe back multiple times sometimes.

**Comment by Hikiru** [comment]
Here’s an example of Apollo’s behavior https://cdn.discordapp.com/attachments/726887643173879890/1161000514721427586/RPReplay_Final1696874419.mov

**Comment by boscojwho** [comment]
We have this feature almost ready to go:
- If you're technically inclined, check out PR #615 =)
- The current implementation scrolls to top, then goes back to the previous page.
- This will ideally be customizable, since every user seems to want a slightly different behaviour =)

**Comment by Hikiru** [comment]
Cool! The scroll to top is what Apollo does too I think, I just didn’t think about it
