### ISSUE TITLE
Allow user to switch target community when composing a post

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#716]
## Introduction
Add a drop-down arrow next to the community name in the post composer view. Clicking on it would bring up a new sheet where the user can search for a community. Clicking on a community result would retarget the post to the selected community.

Before the user enters a search term, we could show the user's subscriptions for easy access.

## Rationale

If the user writes a post then realises they're on the wrong community, they can easily switch without losing their progress.

There are also several features that we may wish to implement later down the line that would rely on this:

- Crossposting: we could let the user swipe on a community result (or use a context menu action) to add the community as a crosspost. 

- Sharing from another app: in the Photos app, we could add a share extension for Mlem that bring up the post composer sheet right within the photos app, uploading the selected image and attaching it to the post automatically. In this situation, we wouldn't already know which community the user wants to post to like we would inside of Mlem itself. Therefore, we'd need a way to search for a community.

**Comment by EricBAndrews** [comment]
Implemented in 2.0 post composer
