### ISSUE TITLE
Website Previews Text Wrapping

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#732]
**Describe the bug**
The website previews text unnecessarily wraps after only a few words.

**Expected Behavior**
Text goes all the way to the edge before wrapping. 

**Mlem Information:**
1.1 (715)

**Additional Context**
![image](https://github.com/mlemgroup/mlem/assets/2528463/5549781e-56d9-4ebc-80d7-696b5515ad18)

**Comment by EricBAndrews** [comment]
Closing--can't repro on 2.0 codebase
