### ISSUE TITLE
Feed scroll to top

### ISSUE THREAD

**Issue by Emiliaaah** [mlemgroup/mlem#742]
## Introduction
In other apps you can press the "home" button ("feeds" in Mlem's case), once you press this button the feed would scroll to the top. This makes it easy to go to the top to then refresh the feed.

## Requirements
Scroll to the top of the feed if you press the feeds button while on the feeds page.

**Comment by boscojwho** [comment]
We do have this feature more or less built (see #615 if you're technically inclined), but it's waiting on some Lemmy v0.19 updates on our end and also some performance issues.
