### ISSUE TITLE
When QuickLookUI is open, rotating device causes it to be dismissed

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#747]
**Describe the bug**

**Expected Behavior**
1. Open photo in Feed.
2. Rotate device.
3. QuickLookUI rotates photo.
4. User continues interacting with QuickLookUI.

**Actual Behavior**
1. Open photo in Feed.
2. Rotate device.
3. QuickLookUI sheet is dismissed.

**To Reproduce**
This happens when opening QuickLookUI from Feed view, but not Post view.
- It doesn't happen if Feed isn't scrolled down past a few posts.

**Mlem Information:**
Latest public TestFlight build and latest dev build.

**Additional Context**

https://github.com/mlemgroup/mlem/assets/2549615/5c2b4ae1-2a48-4fa0-8499-102605229798

**Comment by boscojwho** [comment]
This issue is caused by `FeedView` not respecting scroll position on device rotation. 
- Currently, QuickLookUI is presented as a fullscreen sheet on the `CachedImage` view that trigger its opening.
- This view is associated with a cell in the FeedView.
- On device rotation, `FeedView`'s lazy v stack moves to a different scroll position, and causes the CachedImage view that presented the QuickLookUI to disappear.
- Since the view that presented it disappeared, SwiftUI removes the fullscreen sheet QuickLookUI from view.

We can confirm this by presenting QuickLookUI on a parent view (i.e. `FeedView`):
- Doing so resolves this bug.

I'm not proposing we move the sheet to a parent view (for now, at least).

**Comment by EricBAndrews** [comment]
Closed in #756
