### ISSUE TITLE
POST /site CreateSite

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#76]
I'm abstracting this out of mlemgroup/mlem#52 because it has an extremely rare usecase of being only used when first setting up an instance.

We may pair this with an in-app option to deploy instances at some hosting service, *maybe*, but until then, this is basically the rarest API call.

It is also a lot to write down, so I'll ignore it for now (for mlemgroup/mlem#52) and write the other ones.

**Comment by Sjmarf** [comment]
We auto-generate API types now in [lemmy-swift-codegen](https://github.com/mlemgroup/lemmy-swift-codegen), which includes `CreateSite`
