### ISSUE TITLE
Inbox Count Not Resetting

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#763]
**Describe the bug**
Received new. Moment in Inbox. Read message, made sure to mark as read. 

**Expected Behavior**
Inbox count notification to decrement and go away. 

**Actual Behavior**
Nothing. The inbox count remained at (1). 

**To Reproduce**
Get messages. 

**Mlem Information:**
1.1.1 (753)

**Additional Context**
Restarting the app seems to reset the inbox count.

**Comment by EricBAndrews** [comment]
Possibly related: https://lemmy.ml/comment/5818110

**Comment by EricBAndrews** [comment]
Should be fixed in #934
