### ISSUE TITLE
Mlem loses state when in background

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#765]
From Lemmy community:

> Mlem is the app store version 1.1. i thought i was using TestFlight still. Unsure when i switched.
> This most recent time it was under 2 minutes. I opened safari, typed in a search, clocked the link, then a second link, and copied the url, switched back to mlem and it has reloaded. There have also been times i switched to another app, forgot what i eat looking up came back to mlem and it has reloaded (so under 30 seconds out of mlem)
> This appears to only be happening on my ipad pro 11" (2018), my iphone 14 pro appears to not be reloading on app switch.

https://lemmy.ml/comment/5801191

**Comment by boscojwho** [comment]
I haven't debugged this yet, but the Mlem on iPad (TestFlight) does seem to crash when moving into background, so maybe that's what's happening here.

It could be related to windowing/scenes.

**Comment by boscojwho** [comment]
Possibly related to this issue:

<img width="1792" alt="Screenshot 2023-11-24 at 7 17 36 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/4288b63c-60d6-478b-8638-edea828539f2">
