### ISSUE TITLE
Review SwiftUI View initializers

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#771]
`@State`/`@StateObject` variables should use .init(wrappedValue: ), but in some views we are either not using this initializer, or perform logic outside of it before passing a value into the @autoclosure/Value.
- State that only needs to be calculated/initialized once over the view's lifetime needs to use/be calculated in `.init(wrappedValue:)`
- I haven't inspected this in Instruments yet, but it seems like in some places we are preventing SwiftUI from doing its performance optimizations or preventing it from knowing a value only needs to be instantiated once over its lifetime.

Example
<img width="750" alt="Screenshot 2023-11-21 at 4 57 38 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/a4809f38-fde1-45fd-9ea7-33952798a2fc">

Example
![Screenshot 2023-11-21 at 4 59 59 PM](https://github.com/mlemgroup/mlem/assets/2549615/4c0fc078-df37-47fd-b93a-65e53877932e)

**Comment by EricBAndrews** [comment]
Stale, v1
