### ISSUE TITLE
Missing layout widget tracker causes crash on iPad when app re-enters foreground

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#776]
**Describe the bug**
On iPad only, app crashes when re-entering foreground. Probably the cause of issue #765.

**Expected Behavior**
The layout widget tracker should remain in environment across app lifecycle changes.

**Actual Behavior**
Crashes when re-entering foreground, for some reason, layout widget tracker goes missing.

**To Reproduce**
This appears to be reproducible only on iPad:
1. Fresh app launch.
2. Open first post in Feed view.
3. Scroll to bottom of post (optional, I think).
4. Go to device Home Screen.
5. Wait a few seconds.
6. Open app again.
7. App crashes with following error: 
`Thread 1: Fatal error: No ObservableObject of type LayoutWidgetTracker found. A View.environmentObject(_:) for LayoutWidgetTracker may be missing as an ancestor of this view.`

**Mlem Information:**
Latest `/dev` build.

**Additional Context**
- This happens regardless of window/scene setup (i.e. whether one or more Mlem windows are open, or is in split view/slide over).

**Comment by boscojwho** [comment]
Did a quick test and moved layoutWidgetTracker state object init into `ContentView`, and this did not fix issue.

**Comment by boscojwho** [comment]
When app enters background, SwiftUI triggers multiple calls to `HandleLemmyLinksDisplay.navigationDestination` (not sure why it needs to update in the first place):
- On iPad only, the destination for value `.postLinkWithContext(post)` loses its `layoutWidgetTracker` from its environment for some reason if it's not explicitly passed into the destination view.

**Comment by EricBAndrews** [comment]
Fixed in #777
