### ISSUE TITLE
* On Login: “Mlem is unable to fetch your account information”

### ISSUE THREAD

**Issue by berkeley-blue** [mlemgroup/mlem#795]
**Describe the bug**
What did you do to trigger the bug?
try to log in to throwaway account

**Expected Behavior**
What did you expect to happen?
Login

**Actual Behavior**
What actually happened?
Error message as in Title. Login with same credentials via browser works. Unsure if limited to lemmynsfw.com or other instances as well

**To Reproduce**
What steps do I need to take to trigger the bug?
Attempt loging. 

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug
MLem 1.1 (717)
iOS 17.1.1

**Additional Context**
Any other relevant information

**Comment by EricBAndrews** [comment]
This is due to instances updating to the 0.19 release candidate--we've got the fix in TestFlight now, hoping to have it live to the App Store tomorrow!

Keeping this issue open until then.
