### ISSUE TITLE
Handle image save failure

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#802]
Image saving currently fails quietly--`ImageSaver` should throw an error that pops a failure notification.

**Comment by pbellchambers** [comment]
Is this the reason save image does not seem to work at all in 1.2 ?

1. Open any image post
2. Tap and hold image until Details, Save, Share... menu appears
3. Select Save
4. "Image saved" is displayed, but image isn't actually saved anywhere

**Comment by Sjmarf** [comment]
@pbellchambers Yeah, it should be showing an error message instead. It's possible that you may need to allow Mlem to access your photo library in System Settings -> Mlem.
