### ISSUE TITLE
Tapping a Mastodon user link opens that user in the Profile tab, and tapping "< Back" reloads the Tab in an infinite loop

### ISSUE THREAD

**Issue by BrooklynMan** [mlemgroup/mlem#81]
Tapping a Mastodon user link opens that user in the Profile tab, and tapping "< Back" reloads the Tab in an infinite loop. Force-quit app is required to escape.

![IMG_0178](https://github.com/mormaer/Mlem/assets/5836168/d06a414c-2eba-4d4f-b9fe-a65fda0525ce)

**Comment by Sjmarf** [comment]
Probably fixed in 2.0
