### ISSUE TITLE
Large posts will prevent scrolling by using left and right gestures with Voiceover

### ISSUE THREAD

**Issue by WestonHanners** [mlemgroup/mlem#82]
**Describe the bug**
Normally you can iterate over accessibility elements by swiping left and right, but if a really long post is in the feed, it will prevent this. 

**Expected Behavior**
Shouldn't be stopped from scrolling. 

**Actual Behavior**
User is stopped from scrolling.

**Workaround**
Three-finger scroll gesture will work. 

**Mlem Information:**
0.1.0 21

**Additional Context**
![image](https://github.com/mormaer/Mlem/assets/864259/42a3e987-27cb-435e-9205-82abd7be0999)

**Comment by EricBAndrews** [comment]
Flagging 1.0 because accessibility
