### ISSUE TITLE
Be more lenient when parsing instance URL/domain when logging in

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#83]
It seems that multiple users are encountering this; When pasting a URL/domain to log into, we are not very lenient when trying to resolve that URL/domain, requiring a specific setup of trailing or not-trailing paths, with or without `https`, andsoforth, to log in.

We should be more lenient and try more things, if the resolved domain/url does not match the string given, we should display this in small font above/under the composer, to make the user aware of any discrepancy, if it exists.

It is possible that the domain that they log into with is a different domain than the one it federates as, so we should maybe look into resolving this intelligently too, if this comes up.

**Comment by ShadowJonathan** [comment]
Thats search, it has a different parent.

This is about logging in.

**Comment by Sjmarf** [comment]
(Just a reminder that I'm happy to be assigned this one, if needed)

**Comment by mbs** [comment]
Looks like trailing dot in the hostname (which should be valid) also gives "Logged in to [server] as [account]", then "Mlem couldn't fetch you account's information.  File a bug report."
