### ISSUE TITLE
Navigating to a community from the profile shows the subscribed indicator on every post

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#835]
On a community feed, the subscribed indicator should not be shown.

This works already when navigating to a community from the community list, but does not work when navigating to a community from a profile (this is a bug both before or after the profile redesign).

**Comment by boscojwho** [comment]
Is this reproducible all the time? I tried to repro this, but either couldn't or am not looking for the right subscribed indicator.

![Simulator Screen Recording - iPhone 15 Pro - 2024-01-06 at 18 33 08](https://github.com/mlemgroup/mlem/assets/2549615/f12bdca5-0257-4c63-a5e7-1ba8f18bec91)

**Comment by Sjmarf** [comment]
Huh, that's strange. I can't reproduce it anymore, either. It was consistently reproducible when I first discovered it. Maybe it's been fixed accidentally since I did the feed redo... I'll close this for now
