### ISSUE TITLE
Child comments in some posts don't load

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#844]
**Describe the bug**
Child comments don't load in the following posts in Mlem, but they do in web browser:
- https://lemmy.world/post/1044707
- https://lemm.ee/post/843533

**Expected Behaviour**
1. Open "Subscribed" feed.
2. Select "Most Comments" sort option.
3. Open top posts, expecting to see child comments.

**Actual Behavior**
- App shows that there are comment replies on the parent comment, but nothing appears.

**To Reproduce**
- Not sure, but both those posts are over 6 months old.

**Mlem Information:**
- Latest commit on `/dev` branch.

**Comment by EricBAndrews** [comment]
Can't repro on latest dev build

**Comment by boscojwho** [comment]
Odd, I see it on dev (simulator) and on TestFlight build (device), replies are missing in app but not in browser:
- Compare the first comment in this post below in app vs browser version

<img width="480" alt="Screenshot 2024-02-02 at 8 34 54 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/1c661615-0efc-4635-95af-7032435458d0">

<img width="480" alt="Screenshot 2024-02-02 at 8 34 54 PM" src="https://github.com/mlemgroup/mlem/assets/2549615/6b20e42b-5ff3-4443-8d01-cac5c3d406d2">

**Comment by Sjmarf** [comment]
This is something I think we should support in v2.0; I left some notes on how we could do that in the issue linked above

**Comment by EricBAndrews** [comment]
I _think_ this is fixed with the new comment page
