### ISSUE TITLE
"Search Anything" Search (Tab Button)

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#85]
Given that Lemmy is a Fediverse application, we can send it links to ["resolve"](https://github.com/buresdv/Mlem/issues/71#issuecomment-1585603265) to understandable objects, such as Communities, Users, Posts, or Comments.

We should make this a tab button too, since it seems the users cannot find the search bar (hidden as the "dropdown" section of the main feed)

**Comment by Sjmarf** [comment]
Use the "Search" tab to search. In Mlem v1 we had a "Top Results" tab in search that aggregated results from different categories - we're removing this in Mlem v2 (more info [here](https://github.com/mlemgroup/mlem/issues/939#issuecomment-2036652199)).
