### ISSUE TITLE
List/find popular communities

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#86]
A way to do a "general search" for communities, and arrange them by active users, subscribers, and all those metrics.

Lemmy-UI has this with the "Communities" tab, where one can search between local, subscribed, and "all" communities.

**Comment by EricBAndrews** [comment]
Tentatively slating for 1.1, if the web interface does it we should be able to implement it here

**Comment by irodrigo17** [comment]
I'd love to help with this as well. 

Maybe a "Browse communities" button in the Search tab to navigate to a new page with communities sorted by popularity like the web UI (and with the subscribed / local / all filters)?

I'd probably show just the subscribers to keep it simple on mobile though (ignoring "users / month"), and reuse the existing community cells from the app.

| [Web UI](https://lemmy.world/communities) | Existing community cells |
| --------------- | --------------- |
| ![Simulator Screen Shot - iPhone 14 - 2023-07-20 at 00 24 53](https://github.com/mlemgroup/mlem/assets/1676646/b54c2cf0-5988-4800-95d0-d5ee3c5036e1) | ![IMG_4859](https://github.com/mlemgroup/mlem/assets/1676646/f4453b2b-bda1-4979-9752-d55d447efa6c) |

**Comment by Sjmarf** [comment]
I think we should show the most popular communities in the search tab when no search term is entered. Currently, we show recent searches in this case - instead, we could show recent searches only when the search bar is focused.
