### ISSUE TITLE
Flexible Search

### ISSUE THREAD

**Issue by ShadowJonathan** [mlemgroup/mlem#87]
This is an addon to https://github.com/buresdv/Mlem/issues/83.

Since the API is able to have powerful search, I think it'll be interesting to allow search UX such as (but not limited to);
- Searching posts across communities (by title, description, user, etc.)
- Searching comments across communities (by content, user, etc.)
- Searching users
- Searching communities (this is probably https://github.com/buresdv/Mlem/issues/92)

**Comment by EricBAndrews** [comment]
Tentatively slating for 1.2--very promising idea

**Comment by Sjmarf** [comment]
Maybe search tokens would work well here?

https://www.swiftyplace.com/blog/search-tokens-swiftui-how-to-implement-advanced-search-in-ios-and-macos

**Comment by Sjmarf** [comment]
Added filters in #1316 and #1376.
