### ISSUE TITLE
Reinstate tap tab to navigate in Feeds

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#875]
Per Slack

**Comment by boscojwho** [comment]
Taking a look right now

**Comment by boscojwho** [comment]
cc: pr #874

**Comment by boscojwho** [comment]
Self note:
- Tab navigation on pushed views is broken because on push, `navigationPath.count` reports old value in `NavigationDismissHoisting`.
- This only happens in the updated Feeds tab, `navigationPath.count` reports correct value on push in `NavigationDismissHoisting`.
