### ISSUE TITLE
Clarifying the Search procedure

### ISSUE THREAD

**Issue by Guy-Dudeman** [mlemgroup/mlem#89]
## Introduction
There have been a number of complaints about users not knowing where to click to search. 

## Requirements
The GUI needs to be more intuitive and help guide users to this function.

I propose adding a magnifying glass to the top row, which opens the search, and redesigning the search field within to look more like a search field, with a blinking cursor, so it is more obvious that that is where you type to search.
![LemmyHeader](https://github.com/mormaer/Mlem/assets/136025639/7bea8a3a-ccdf-4b44-be90-ff766a240455)
![LemmySearchFeeds](https://github.com/mormaer/Mlem/assets/136025639/f5b8d073-18f6-4581-acae-ac731620d1a9)

**Comment by WestonHanners** [comment]
I would recommend a search tab.

**Comment by JakeShirley** [comment]
Closing this with the addition of the search tab.
