### ISSUE TITLE
Can't add accounts with the same username on different instances

### ISSUE THREAD

**Issue by andrewgioia** [mlemgroup/mlem#94]
**Describe the bug**

When I add an account for one instance with the same username as an account I already added for a different instance, Mlem shows the first account twice. The communities page is also blank regardless of which account I select here. It seems it cannot handle `user@instance1` and `user@instance2`.

**Expected Behavior**

Both accounts should authenticate fine and exist independently of each other, the server/instance is different only the username is the same.

**Actual Behavior**

Both accounts in the account switcher show the same user and instance (the first one added) and I cannot authenticate as the first one.

**To Reproduce**

1. Add an account to Mlem on one server (e.g., andrew@lemmy.ml)
2. Add an account on a different server but that has the same username as the first account (e.g., andrew@mtgzone.com)
3. Note that both accounts now show the first username/instance (i.e., andrew@lemmy.ml)

**Mlem Information:**

v0.1.0 (19) but this happened on the previous build as well.

**Additional Context**

Screenshots of the workflow:

1. Two existing accounts in Mlem, working correctly
 
   <img src="https://github.com/mormaer/Mlem/assets/221473/7566fe9b-39f5-45fe-ab46-5c26aeb233c2" width="400">

2. Added a second account with the same username as an existing account (andrew), authenticated correctly:

    <img src="https://github.com/mormaer/Mlem/assets/221473/df447aba-7553-4758-a6ff-cc91a82763f3" width="400">

3. Both accounts now show the first user and instance

    <img src="https://github.com/mormaer/Mlem/assets/221473/adb20dd6-e1ed-4640-b53b-7c1843b78bc1" width="400">

**Comment by Sjmarf** [comment]
I'm logged into three instances with the same username, and don't experience this issue.

**Comment by EricBAndrews** [comment]
Should be fixed as of #331
