### ISSUE TITLE
Add Access to Modlog

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#946]
## Introduction
It is my understanding that accessing the modlog for an instance is done by going to https://instance/modlog. This is currently not a feature of mlem. 

## Requirements
Lemmy exposes an API endpoint to access the modlog.

## Discussion
Unofficial documentation can be found at https://lemmy.readme.io/reference/get_modlog

## What I Need
Similar to the web UI, it should show each entry to the modlog.

**Comment by EricBAndrews** [comment]
Slating for 1.3 mod tools work
