### ISSUE TITLE
Favorited communities occasionally show up multiple times

### ISSUE THREAD

**Issue by JakeShirley** [mlemgroup/mlem#95]
**Describe the bug**
One of my favorited communities shows up twice in the community list view

**Expected Behavior**
Each community only shows up once

**Actual Behavior**
Sometimes a community shows up twice.

**To Reproduce**
Not really sure.

**Mlem Information:**
0.1.0

**Additional Context**
![image](https://github.com/mormaer/Mlem/assets/1000311/e9ca2cde-9e87-4ca3-bcec-0335a568f881)

**Comment by Sjmarf** [comment]
This one is resolved, right?
