### ISSUE TITLE
Regional date format not followed on profile page

### ISSUE THREAD

**Issue by pleasegodthinkofausernameforme** [mlemgroup/mlem#951]
**Describe the bug**
Date format following US MM/DD/YYYY format when system set to international DD/MM/YYYY format,

**Expected Behavior**
Correct system date format to be followed

**Actual Behavior**
MM/DD shown

version 1.2
![IMG_8601](https://github.com/mlemgroup/mlem/assets/145724153/139fec85-0404-46a2-a59d-7d9f14a8c314)

**Comment by Sjmarf** [comment]
I can't reproduce this one. The date format is shown correctly for me when I set my phone's region to the United Kingdom, and is shown correctly for the United States too. 

In System Settings -> General -> Language & Region what have you got "Region" set to? And what about "Date Format"?
