### ISSUE TITLE
Mlem client slows down to a crawl after subscribing to hundreds of communities

### ISSUE THREAD

**Issue by Ralimbahere** [mlemgroup/mlem#958]
I have subscribed to 872 communities after finding many on !trendingcommunities.

I was hoping the app would maintain its normal speed.

The app became too slow to use. Such as loading posts or tapping into comments.

There is a threshold before performance is impacted.

Iphone 13 Pro + IOS 17.3.1 + 1.2 + 847

**Comment by Sjmarf** [comment]
Yep, I can repro this. Navigating forward and backward has a good couple seconds of delay. 

We're currently working on a complete rewrite of the app structure, in which I'll try to fix this.

**Comment by Ralimbahere** [comment]
I'm glad I'm not the only who broke their Mlem client haha ;)
