### ISSUE TITLE
* No posts from Lemmy.ca

### ISSUE THREAD

**Issue by graham-pyett** [mlemgroup/mlem#97]
**Describe the bug**
On my main feed, I only see posts from a few select instances (lemmy.ml, beehaw, and a few others) and it's the same posts over and over. On my home lemmy instance in a browser I see tons more content from many more communities, but most of them are hosted on lemmy.ca.

I can, however see a featured post on !main@lemmy.ca and one post from !canada@lemmy.ca

But posts on !saskatoon@lemmy.ca, for example, are not visible at all

**Expected Behavior**
I expect my feed on the app to be more or less the same as what it is on a browser

**Actual Behavior**
It's not the same, many posts are missing

**To Reproduce**
Be subscribed to communities on lemmy.ca and then open the main feed

**Mlem Information:**
Version + Build number 0.0.6
If this started happening recently, write which version introduced the bug

**Additional Context**
Any other relevant information

**Comment by sharpjs** [comment]
As a Lemmy.ca user, this issue is long resolved for me. I remember the issue occurring with one of Mlem, Memmy, or Voyager — I don't remember which. The issue resolved itself a few days later.
